import { useMemo, useState } from "react";
import { DataTable } from "../components/DataTable";
import { FilterBar } from "../components/FilterBar";
import { PageHeader } from "../components/PageHeader";
import { SearchInput } from "../components/SearchInput";
import { StatusBadge } from "../components/StatusBadge";
import { commissions } from "../data/commissions";
import { formatPkr } from "../data/adminData";

export function CommissionsPage() { const [search, setSearch] = useState(""); const [provider, setProvider] = useState("All"); const [service, setService] = useState("All"); const rows = useMemo(() => commissions.filter((item) => (!search || item.bookingReference.toLowerCase().includes(search.toLowerCase())) && (provider === "All" || item.provider === provider) && (service === "All" || item.serviceType === service)), [search, provider, service]); return <><PageHeader eyebrow="GFIX FINANCE" title="Commissions" description="Track expected GFix commission by booking service and provider."/><FilterBar resultText={`${rows.length} commission records`} onClear={() => { setSearch(""); setProvider("All"); setService("All"); }}><SearchInput value={search} onChange={setSearch} placeholder="Search booking reference"/><select className="field" value={provider} onChange={(e) => setProvider(e.target.value)}><option>All</option>{[...new Set(commissions.map((item) => item.provider))].map((value) => <option key={value}>{value}</option>)}</select><select className="field" value={service} onChange={(e) => setService(e.target.value)}><option>All</option>{[...new Set(commissions.map((item) => item.serviceType))].map((value) => <option key={value}>{value}</option>)}</select></FilterBar><DataTable rows={rows} rowKey={(row) => row.id} columns={[{ key: "booking", label: "Booking", render: (row) => <strong className="text-river">{row.bookingReference}</strong> }, { key: "service", label: "Service", render: (row) => row.serviceType }, { key: "provider", label: "Provider", render: (row) => row.provider }, { key: "gross", label: "Gross amount", render: (row) => formatPkr(row.grossAmount) }, { key: "rate", label: "Rate", render: (row) => `${row.commissionRate}%` }, { key: "amount", label: "Commission", render: (row) => <strong>{formatPkr(row.commissionAmount)}</strong> }, { key: "status", label: "Status", render: (row) => <StatusBadge status={row.status === "Cleared" ? "Completed" : row.status === "Pending" ? "Pending" : "Confirmed"}/> }, { key: "date", label: "Date", render: (row) => row.date }]}/></>; }
