import { FormEvent, useState } from "react";
import { Mail, Send, Volume2 } from "lucide-react";
import { PageHeader } from "../components/PageHeader";
import { usePreviewState } from "../hooks/usePreviewState";
import { playPreviewTone } from "../lib/notificationTone";

type Inquiry = { id: string; name: string; email: string; topic: string; message: string; status: "New" | "In progress" | "Closed"; receivedAt: string };
const seed: Inquiry[] = [{ id: "contact-1", name: "Nida Khan", email: "nida@example.com", topic: "Custom trip", message: "Can you help with a five-day family route starting in Islamabad?", status: "New", receivedAt: "Today, 10:20 AM" }];
export function ContactInboxPage() { const [rows, setRows] = usePreviewState("swatstay.admin.contact-inbox.preview", seed); const [selectedId, setSelectedId] = useState(rows[0].id); const [reply, setReply] = useState(""); const selected = rows.find((item) => item.id === selectedId) ?? rows[0]; function send(event: FormEvent) { event.preventDefault(); if (!selected || !reply.trim()) return; setRows((current) => current.map((item) => item.id === selected.id ? { ...item, status: "In progress" } : item)); setReply(""); } return <><PageHeader eyebrow="PUBLIC CONTACT" title="Contact inbox" description="Review website contact requests and prepare branded email replies. Sending is not connected until the email service is approved." actions={<button className="button-secondary" onClick={playPreviewTone}><Volume2 size={15}/> Test new-request tone</button>}/><div className="grid gap-4 xl:grid-cols-[320px_minmax(0,1fr)]"><aside className="overflow-hidden rounded-lg border border-border bg-white">{rows.map((item) => <button key={item.id} onClick={() => setSelectedId(item.id)} className={`w-full border-b border-border p-4 text-left ${item.id === selected?.id ? "bg-mist" : "hover:bg-snow"}`}><div className="flex justify-between gap-2"><strong className="text-sm text-charcoal">{item.name}</strong><span className="text-xs text-stone">{item.status}</span></div><p className="mt-1 text-xs text-river">{item.topic}</p><p className="mt-2 line-clamp-2 text-xs text-stone">{item.message}</p></button>)}</aside>{selected && <section className="rounded-lg border border-border bg-white p-5"><div className="flex items-center gap-2"><Mail size={18} className="text-river"/><div><h2 className="font-bold text-charcoal">{selected.topic}</h2><p className="text-xs text-stone">{selected.name} · {selected.email} · {selected.receivedAt}</p></div></div><p className="mt-5 rounded-md bg-snow p-4 text-sm leading-6 text-charcoal">{selected.message}</p><form onSubmit={send} className="mt-5"><label className="label">Branded reply preview<textarea required className="field mt-1.5 min-h-36 py-3" value={reply} onChange={(event) => setReply(event.target.value)} placeholder={`Hello ${selected.name},\n\nThank you for contacting SwatStay...`}/></label><button className="button-primary mt-3"><Send size={15}/> Prepare email reply</button><p className="mt-2 text-xs text-stone">Frontend preview only. Email will be sent through the future notification service, with delivery status saved to the inquiry.</p></form></section>}</div></>; }
