import { Edit3, Eye, Save, Send } from "lucide-react";
import { FormEvent, useState } from "react";
import { AdminModal } from "../components/AdminModal";
import { PageHeader } from "../components/PageHeader";
import { StatusBadge } from "../components/StatusBadge";
import { contentSections as initialSections } from "../data/content";
import type { ContentSection } from "../types/admin";

export function ContentPage() { const [sections, setSections] = useState(initialSections); const [selected, setSelected] = useState<ContentSection | null>(null); const [draft, setDraft] = useState(""); const [message, setMessage] = useState(""); function save(event: FormEvent, publish: boolean) { event.preventDefault(); if (!selected) return; setSections((current) => current.map((item) => item.id === selected.id ? { ...item, preview: draft, status: publish ? "Published" : "Draft" } : item)); setMessage(publish ? "Published in frontend state." : "Draft saved in frontend state."); } return <><PageHeader eyebrow="PUBLIC WEBSITE CONTENT" title="Website content" description="Prepare homepage, legal, help, contact, and global content for future API publishing."/><div className="grid gap-3 lg:grid-cols-2">{sections.map((section) => <article key={section.id} className="rounded-lg border border-border bg-white p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-semibold text-river">{section.area}</span><h2 className="mt-1 font-bold text-charcoal">{section.title}</h2></div><StatusBadge status={section.status === "Published" ? "Confirmed" : "Pending"}/></div><p className="mt-3 min-h-12 rounded-md bg-snow p-3 text-sm leading-5 text-stone">{section.preview}</p><div className="mt-4 flex gap-2"><button type="button" className="button-secondary" onClick={() => { setSelected(section); setDraft(section.preview); setMessage(""); }}><Edit3 size={15}/> Edit</button><button type="button" className="button-secondary" onClick={() => { setSelected(section); setDraft(section.preview); setMessage("Preview opened with current frontend content."); }}><Eye size={15}/> Preview</button></div></article>)}</div><AdminModal open={Boolean(selected)} onClose={() => setSelected(null)} title={`Edit ${selected?.title ?? "content"}`} description="Structured frontend content editor"><form onSubmit={(e) => save(e, false)}><label className="label">Content<textarea className="field mt-1.5 min-h-44 resize-y py-3" value={draft} onChange={(e) => { setDraft(e.target.value); setMessage(""); }} required/></label>{message && <p className="mt-3 rounded-md bg-[#e8f1ec] p-3 text-sm font-semibold text-pine">{message}</p>}<div className="mt-4 flex justify-end gap-2"><button type="submit" className="button-secondary"><Save size={15}/> Save draft</button><button type="button" className="button-primary" onClick={(e) => save(e as unknown as FormEvent, true)}><Send size={15}/> Publish</button></div></form></AdminModal></>; }
