import { Edit3, Image, Plus } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { AdminModal } from "../components/AdminModal";
import { FileUploadPlaceholder } from "../components/FileUploadPlaceholder";
import { FormField } from "../components/FormField";
import { PageHeader } from "../components/PageHeader";
import { StatusBadge } from "../components/StatusBadge";
import { adminDestinations as initialDestinations } from "../data/destinations";
import type { DestinationAdmin } from "../types/admin";

export function DestinationsPage() { const [items, setItems] = useState(initialDestinations); const [editing, setEditing] = useState<DestinationAdmin | null>(null); const [open, setOpen] = useState(false); function edit(item?: DestinationAdmin) { setEditing(item ?? null); setOpen(true); } function save(item: DestinationAdmin) { setItems((current) => editing ? current.map((entry) => entry.id === item.id ? item : entry) : [...current, item]); setOpen(false); } return <><PageHeader eyebrow="DESTINATION CONTENT" title="Destinations" description="Manage destination cards, travel details, images, and search metadata." actions={<button type="button" className="button-primary" onClick={() => edit()}><Plus size={15}/> Add destination</button>}/><section className="overflow-hidden rounded-lg border border-border bg-white"><div className="divide-y divide-border">{items.map((item) => <article key={item.id} className="grid gap-4 p-4 md:grid-cols-[1fr_180px_auto] md:items-center"><div><div className="flex items-center gap-2"><h2 className="font-bold text-charcoal">{item.name}</h2><StatusBadge status={item.status === "Active" ? "Active" : "Completed"}/></div><p className="mt-1 text-sm text-stone">{item.shortDescription}</p><p className="mt-2 text-xs text-stone">Best for: {item.bestFor} · From Mingora: {item.travelTime}</p></div><div className="flex items-center gap-2 text-sm text-stone"><Image size={16} className="text-river"/> Cover and gallery</div><div className="flex gap-2"><button type="button" className="button-secondary" onClick={() => edit(item)}><Edit3 size={15}/> Edit</button><button type="button" className="button-secondary" onClick={() => setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, status: entry.status === "Active" ? "Inactive" : "Active" } : entry))}>{item.status === "Active" ? "Deactivate" : "Activate"}</button></div></article>)}</div></section><DestinationEditor open={open} item={editing} onClose={() => setOpen(false)} onSave={save}/></>; }

function DestinationEditor({ open, item, onClose, onSave }: { open: boolean; item: DestinationAdmin | null; onClose: () => void; onSave: (item: DestinationAdmin) => void }) { const [form, setForm] = useState(item ?? initialDestinations[0]); useEffect(() => { if (open) setForm(item ?? { ...initialDestinations[0], id: `dest-${Date.now()}`, name: "", slug: "", status: "Inactive" }); }, [item, open]); function submit(e: FormEvent) { e.preventDefault(); onSave(form); } return <AdminModal open={open} onClose={onClose} title={item ? "Edit destination" : "Add destination"} width="max-w-3xl"><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><FormField label="Name"><input className="field mt-1.5" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/></FormField><FormField label="Slug"><input className="field mt-1.5" value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })}/></FormField><FormField label="Short description"><textarea className="field mt-1.5 min-h-24 py-3" value={form.shortDescription} onChange={(e) => setForm({ ...form, shortDescription: e.target.value })}/></FormField><FormField label="Full description"><textarea className="field mt-1.5 min-h-24 py-3" value={form.fullDescription} onChange={(e) => setForm({ ...form, fullDescription: e.target.value })}/></FormField><FormField label="Best for"><input className="field mt-1.5" value={form.bestFor} onChange={(e) => setForm({ ...form, bestFor: e.target.value })}/></FormField><FormField label="Travel time from Mingora"><input className="field mt-1.5" value={form.travelTime} onChange={(e) => setForm({ ...form, travelTime: e.target.value })}/></FormField><FileUploadPlaceholder label="Destination cover"/><FileUploadPlaceholder label="Gallery images"/><FormField label="SEO title"><input className="field mt-1.5" value={form.seoTitle} onChange={(e) => setForm({ ...form, seoTitle: e.target.value })}/></FormField><FormField label="SEO description"><textarea className="field mt-1.5 min-h-24 py-3" value={form.seoDescription} onChange={(e) => setForm({ ...form, seoDescription: e.target.value })}/></FormField><button type="submit" className="button-primary md:col-span-2">Save destination</button></form></AdminModal>; }
