import { FileText, Save } from "lucide-react";
import { useState } from "react";
import { PageHeader } from "../components/PageHeader";
import { usePreviewState } from "../hooks/usePreviewState";

type LegalDoc = { id: string; title: string; summary: string; content: string; version: string; status: "Draft" | "Published" };
const seed: LegalDoc[] = [
  { id: "terms", title: "Terms and Conditions", summary: "Booking, cancellation, provider coordination, and payment terms.", content: "Final booking terms are confirmed during the call and recorded with the booking.", version: "1.0", status: "Published" },
  { id: "privacy", title: "Privacy Policy", summary: "Traveler, provider, document, support, and retention information.", content: "Collect only the data needed for travel coordination and lawful operations.", version: "1.0", status: "Published" },
  { id: "cancellation", title: "Cancellation Policy", summary: "Cancellation, refund, weather, road, and rescheduling rules.", content: "Provider policy and booking timing determine refund eligibility.", version: "1.0", status: "Draft" },
];
export function LegalPage() { const [docs, setDocs] = usePreviewState("swatstay.admin.legal.preview", seed); const [selected, setSelected] = useState(docs[0].id); const doc = docs.find((item) => item.id === selected) ?? docs[0]; return <><PageHeader eyebrow="PUBLIC WEBSITE" title="Legal content" description="Maintain the Terms, Privacy, and cancellation copy that will publish to the public website after review."/><div className="grid gap-4 lg:grid-cols-[260px_minmax(0,1fr)]"><aside className="space-y-2">{docs.map((item) => <button key={item.id} onClick={() => setSelected(item.id)} className={`w-full rounded-lg border p-3 text-left ${item.id === doc.id ? "border-river bg-mist" : "border-border bg-white"}`}><strong className="block text-sm text-charcoal">{item.title}</strong><span className="mt-1 block text-xs text-stone">v{item.version} · {item.status}</span></button>)}</aside><section className="rounded-lg border border-border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><div className="eyebrow">LEGAL DOCUMENT</div><h2 className="mt-1 text-xl font-bold text-charcoal">{doc.title}</h2><p className="mt-2 text-sm text-stone">{doc.summary}</p></div><FileText className="text-river"/></div><label className="label mt-5 block">Public content<textarea className="field mt-1.5 min-h-56 py-3" value={doc.content} onChange={(event) => setDocs((current) => current.map((item) => item.id === doc.id ? { ...item, content: event.target.value, status: "Draft" } : item))}/></label><div className="mt-4 flex flex-wrap gap-2"><button className="button-secondary" onClick={() => setDocs((current) => current.map((item) => item.id === doc.id ? { ...item, version: String(Number(item.version) + .1), status: "Draft" } : item))}><Save size={15}/> Save draft</button><button className="button-primary" onClick={() => setDocs((current) => current.map((item) => item.id === doc.id ? { ...item, status: "Published" } : item))}>Publish legal copy</button></div><p className="mt-4 text-xs text-stone">Frontend preview only. Legal approval, version audit history, and public deployment require the API and content-release workflow.</p></section></div></>; }
