import { Copy, Eye, FileImage, Trash2, UploadCloud } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { AdminModal } from "../components/AdminModal";
import { PageHeader } from "../components/PageHeader";
import { SearchInput } from "../components/SearchInput";
import { mediaAssets as fallbackAssets } from "../data/media";
import { adminRequest, getAdminToken } from "../lib/adminApi";
import type { MediaAsset } from "../types/admin";

type LiveMedia = { id: string; name: string; mimeType: string; size: number; url?: string | null };
const formatSize = (bytes: number) => bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.round(bytes / 1024))} KB`;

export function MediaPage() {
  const [assets, setAssets] = useState<MediaAsset[]>(getAdminToken() ? [] : fallbackAssets);
  const [search, setSearch] = useState(""); const [type, setType] = useState("All"); const [selected, setSelected] = useState<MediaAsset | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(Boolean(getAdminToken()));
  async function load() { if (!getAdminToken()) return; setLoading(true); try { const data = await adminRequest<LiveMedia[]>("/admin/media"); setAssets(data.map((item) => ({ id: item.id, name: item.name, type: item.mimeType.includes("pdf") ? "Document" : "Image", url: item.url ?? "", size: formatSize(item.size), usedBy: "Not assigned" }))); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load media."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => assets.filter((asset) => (!search || asset.name.toLowerCase().includes(search.toLowerCase())) && (type === "All" || asset.type === type)), [assets, search, type]);
  async function upload(files: FileList | null) { const file = files?.[0]; if (!file) return; if (file.size > 10 * 1024 * 1024) { setError("Files must be 10 MB or smaller."); return; } if (!getAdminToken()) { setMessage("Sign in as admin or operations to upload to Supabase Storage."); return; } const form = new FormData(); form.append("file", file); try { await adminRequest("/admin/media", { method: "POST", body: form }); setMessage("Media uploaded to the private bucket."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Upload failed."); } }
  async function remove(asset: MediaAsset) { if (!getAdminToken()) { setAssets((current) => current.filter((item) => item.id !== asset.id)); return; } try { await adminRequest("/admin/media", { method: "DELETE", body: JSON.stringify({ path: asset.id }) }); setAssets((current) => current.filter((item) => item.id !== asset.id)); setMessage("Media deleted from private storage."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Delete failed."); } }
  async function copy(asset: MediaAsset) { if (asset.url) { await navigator.clipboard?.writeText(asset.url); setMessage("Temporary preview URL copied."); } }
  return <><PageHeader eyebrow="ASSET OPERATIONS" title="Media library" description="Upload and review protected images and documents used by packages, destinations, providers, and operations." actions={<label className="button-primary cursor-pointer"><UploadCloud size={15}/> Upload media<input hidden type="file" accept="image/*,.pdf" onChange={(event) => void upload(event.target.files)}/></label>}/>{loading && <p className="mb-4 rounded-md border border-border bg-white p-3 text-sm text-stone">Loading private media...</p>}{error && <p className="mb-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mb-4 grid gap-3 rounded-lg border border-border bg-white p-3 md:grid-cols-[1fr_260px]"><SearchInput value={search} onChange={setSearch} placeholder="Search media"/><select className="field" value={type} onChange={(e) => setType(e.target.value)}><option>All</option>{[...new Set(assets.map((asset) => asset.type))].map((value) => <option key={value}>{value}</option>)}</select></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{visible.map((asset) => <article key={asset.id} className="overflow-hidden rounded-lg border border-border bg-white">{asset.url && asset.type === "Image" ? <img src={asset.url} alt="" className="h-36 w-full object-cover"/> : <div className="grid h-36 place-items-center bg-mist text-sm font-semibold text-stone"><FileImage size={25}/></div>}<div className="p-3"><span className="text-xs font-semibold text-river">{asset.type}</span><h2 className="mt-1 truncate text-sm font-bold text-charcoal">{asset.name}</h2><p className="mt-1 text-xs text-stone">{asset.size} · {asset.usedBy}</p><div className="mt-3 flex gap-2"><button type="button" className="icon-button" onClick={() => setSelected(asset)} aria-label="Preview media"><Eye size={15}/></button><button type="button" className="icon-button" onClick={() => void copy(asset)} aria-label="Copy signed media URL"><Copy size={15}/></button><button type="button" className="icon-button ml-auto text-[#9c3f2e]" onClick={() => void remove(asset)} aria-label="Delete media"><Trash2 size={15}/></button></div></div></article>)}</div>{!visible.length && !loading && <div className="rounded-lg border border-dashed border-border bg-white p-8 text-center text-sm text-stone">No media matches these filters.</div>}{message && <div role="status" className="fixed bottom-4 right-4 z-40 rounded-md bg-pine px-4 py-3 text-sm font-semibold text-white shadow-panel">{message}</div>}<AdminModal open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.name ?? "Media preview"} description={selected?.type}>{selected?.url ? <img src={selected.url} alt={selected.name} className="max-h-[60vh] w-full rounded-lg object-contain"/> : <div className="grid min-h-64 place-items-center rounded-lg bg-mist text-sm text-stone">Preview unavailable for this file.</div>}</AdminModal></>;
}
