import { Check, Eye, FileImage, X } from "lucide-react";
import { useMemo, useState } from "react";
import { AdminModal } from "../components/AdminModal";
import { PageHeader } from "../components/PageHeader";
import { PaymentBadge } from "../components/PaymentBadge";
import { formatPkr, payments as initialPayments } from "../data/adminData";
import { useBookingsPreview } from "../hooks/useBookingsPreview";
import { workflowBlockReason } from "../lib/bookingWorkflow";
import { usePreviewState } from "../hooks/usePreviewState";
import type { Payment } from "../types/admin";

export function PaymentsPage() {
  const [payments, setPayments] = usePreviewState("swatstay.admin.payments.preview", initialPayments);
  const { bookings, updateBooking } = useBookingsPreview();
  const [selected, setSelected] = useState<Payment | null>(null);
  const [reviewStatus, setReviewStatus] = useState<Payment["status"] | null>(null);
  const [status, setStatus] = useState("All"); const [method, setMethod] = useState("All"); const [date, setDate] = useState(""); const [note, setNote] = useState("");
  const [gateMessage, setGateMessage] = useState("");
  const visible = useMemo(() => payments.filter((item) => (status === "All" || item.status === status) && (method === "All" || item.method === method) && (!date || item.submittedAt.startsWith(date))), [payments, status, method, date]);
  const openReview = (payment: Payment, next: Payment["status"]) => { const linked = bookings.find((booking) => booking.reference === payment.bookingReference); const blocked = linked ? workflowBlockReason(linked, "payment") : null; if (blocked) { setGateMessage(`${payment.bookingReference} is locked. ${blocked}`); return; } setGateMessage(""); setSelected(payment); setReviewStatus(next); setNote(payment.note ?? ""); };
  const saveReview = () => {
    if (!selected || !reviewStatus || (reviewStatus === "Rejected" && !note.trim())) return;
    setPayments((current) => current.map((payment) => payment.id === selected.id ? { ...payment, status: reviewStatus, note: note.trim(), verifiedBy: reviewStatus === "Verified" ? "Current admin" : undefined, verifiedAt: reviewStatus === "Verified" ? "Just now" : undefined } : payment));
    const linked = bookings.find((booking) => booking.reference === selected.bookingReference);
    if (linked) updateBooking(linked.id, { paymentStatus: reviewStatus });
    setSelected(null); setReviewStatus(null);
  };
  return <><PageHeader eyebrow="FINANCE OPERATIONS" title="Payment proofs" description="Review proof, record a reason, and update the linked booking in this browser-only preview."/>
    {gateMessage && <div className="mb-4 rounded-md border border-[#ecd3ad] bg-[#fbf3e6] p-3 text-sm text-[#925d19]">{gateMessage}</div>}<div className="mb-4 grid gap-3 rounded-lg border border-border bg-white p-3 md:grid-cols-3"><select className="field" value={status} onChange={(e) => setStatus(e.target.value)}><option>All</option><option>Proof submitted</option><option>Verified</option><option>Rejected</option></select><select className="field" value={method} onChange={(e) => setMethod(e.target.value)}><option>All</option>{[...new Set(payments.map((item) => item.method))].map((value) => <option key={value}>{value}</option>)}</select><input type="date" className="field" value={date} onChange={(e) => setDate(e.target.value)}/></div>
    <section className="overflow-hidden rounded-lg border border-border bg-white"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[980px] text-left"><thead className="border-b border-border bg-mist text-xs uppercase text-stone"><tr><th className="px-4 py-3">Booking</th><th className="px-4 py-3">Tourist</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Method</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Reviewed by</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-border">{visible.map((payment) => <tr key={payment.id} className="hover:bg-snow"><td className="px-4 py-3 text-sm font-bold text-river">{payment.bookingReference}</td><td className="px-4 py-3 text-sm font-semibold text-charcoal">{payment.touristName}</td><td className="px-4 py-3 text-sm text-charcoal">{formatPkr(payment.amount)}</td><td className="px-4 py-3 text-sm text-stone">{payment.method}</td><td className="px-4 py-3"><PaymentBadge status={payment.status}/></td><td className="px-4 py-3 text-xs text-stone">{payment.verifiedBy ?? "Not reviewed"}<span className="block">{payment.verifiedAt}</span></td><td className="px-4 py-3"><div className="flex justify-end gap-2"><button type="button" className="icon-button" onClick={() => openReview(payment, payment.status)} aria-label="View payment proof"><Eye size={16}/></button><button type="button" className="icon-button text-pine" onClick={() => openReview(payment, "Verified")} aria-label="Verify payment"><Check size={16}/></button><button type="button" className="icon-button text-[#9c3f2e]" onClick={() => openReview(payment, "Rejected")} aria-label="Reject payment"><X size={16}/></button></div></td></tr>)}</tbody></table></div>
      <div className="divide-y divide-border md:hidden">{visible.map((payment) => <article key={payment.id} className="p-4"><div className="flex justify-between gap-3"><div><span className="text-xs font-bold text-river">{payment.bookingReference}</span><h2 className="mt-1 font-semibold text-charcoal">{payment.touristName}</h2></div><PaymentBadge status={payment.status}/></div><p className="mt-3 text-sm text-stone">{formatPkr(payment.amount)} · {payment.method}</p><div className="mt-4 flex gap-2"><button type="button" className="button-secondary" onClick={() => openReview(payment, payment.status)}><Eye size={15}/> Proof</button><button type="button" className="button-primary ml-auto" onClick={() => openReview(payment, "Verified")}><Check size={15}/> Verify</button><button type="button" className="button-secondary text-[#9c3f2e]" onClick={() => openReview(payment, "Rejected")}><X size={15}/> Reject</button></div></article>)}</div></section>
    <AdminModal open={Boolean(selected)} onClose={() => { setSelected(null); setReviewStatus(null); }} title={`Payment proof · ${selected?.bookingReference ?? ""}`} description="Frontend review only. The linked booking is updated in this browser.">{selected && <><div className="grid min-h-48 place-items-center rounded-lg border border-dashed border-border bg-snow text-center"><div><FileImage className="mx-auto text-river" size={30}/><strong className="mt-3 block text-sm text-charcoal">{selected.proofFileName ?? "Payment proof file"}</strong><p className="mt-1 text-xs text-stone">{selected.referenceNumber} · {selected.method}</p><p className="mt-1 text-xs text-stone">{formatPkr(selected.amount)} · submitted {selected.submittedAt}</p></div></div><label className="label mt-4">{reviewStatus === "Rejected" ? "Rejection reason" : "Finance note"}<textarea required={reviewStatus === "Rejected"} className="field mt-1.5 min-h-24 py-3" value={note} onChange={(e) => setNote(e.target.value)} placeholder={reviewStatus === "Rejected" ? "Explain what the traveler needs to correct" : "Record the review context"}/></label>{reviewStatus === "Rejected" && !note.trim() && <p className="mt-2 text-xs text-[#9c3f2e]">A rejection reason is required.</p>}<button type="button" className="button-primary mt-3 w-full" disabled={reviewStatus === "Rejected" && !note.trim()} onClick={saveReview}>{reviewStatus === "Verified" ? "Confirm verification" : reviewStatus === "Rejected" ? "Confirm rejection" : "Save note"}</button></>}</AdminModal>
  </>;
}
