import { FormEvent, useState } from "react";
import { Check, NotebookPen } from "lucide-react";
import { AdminModal } from "../components/AdminModal";
import { DataTable } from "../components/DataTable";
import { PageHeader } from "../components/PageHeader";
import { StatusBadge } from "../components/StatusBadge";
import { formatPkr } from "../data/adminData";
import { payouts as initialPayouts } from "../data/payouts";
import { usePreviewState } from "../hooks/usePreviewState";
import type { PayoutRecord } from "../types/admin";

type PayoutReview = { row: PayoutRecord; mode: "note" | "pay" };
export function PayoutsPage() { const [rows, setRows] = usePreviewState("swatstay.admin.payouts", initialPayouts); const [selected, setSelected] = useState<PayoutReview | null>(null); const [note, setNote] = useState(""); const [reference, setReference] = useState(""); function open(row: PayoutRecord, mode: PayoutReview["mode"]) { setSelected({ row, mode }); setNote(row.note); setReference(""); } function save(e: FormEvent) { e.preventDefault(); if (!selected || (selected.mode === "pay" && !reference.trim())) return; setRows((current) => current.map((item) => item.id === selected.row.id ? { ...item, note: selected.mode === "pay" ? `${note.trim()}${note.trim() ? " | " : ""}Paid ${new Date().toLocaleDateString("en-PK")} · ${reference.trim()}` : note, status: selected.mode === "pay" ? "Paid" : item.status, paidAmount: selected.mode === "pay" ? item.amount : item.paidAmount, pendingBalance: selected.mode === "pay" ? 0 : item.pendingBalance } : item)); setSelected(null); } return <><PageHeader eyebrow="PROVIDER FINANCE" title="Payouts" description="Record a payment reference and confirmation in the shared admin record."/><DataTable rows={rows} rowKey={(row) => row.id} columns={[{ key: "provider", label: "Provider", render: (row) => <strong>{row.provider}</strong> }, { key: "amount", label: "Payout amount", render: (row) => formatPkr(row.amount) }, { key: "pending", label: "Pending balance", render: (row) => formatPkr(row.pendingBalance) }, { key: "paid", label: "Paid amount", render: (row) => formatPkr(row.paidAmount) }, { key: "method", label: "Method", render: (row) => row.method }, { key: "status", label: "Status", render: (row) => <StatusBadge status={row.status === "Paid" ? "Completed" : row.status === "Pending" ? "Pending" : "Provider selection"}/> }, { key: "actions", label: "Actions", render: (row) => <div className="flex gap-2"><button type="button" className="icon-button" title="Add payout note" onClick={() => open(row, "note")}><NotebookPen size={15}/></button><button type="button" className="button-secondary" disabled={row.status === "Paid"} onClick={() => open(row, "pay")}><Check size={15}/> Mark paid</button></div> }]}/><AdminModal open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.mode === "pay" ? "Confirm provider payout" : "Add payout note"} description={selected?.row.provider}><form onSubmit={save} className="space-y-4">{selected?.mode === "pay" && <label className="label">Payment reference<input required className="field mt-1.5" value={reference} onChange={(e) => setReference(e.target.value)} placeholder="Bank transfer or wallet reference"/></label>}<label className="label">{selected?.mode === "pay" ? "Confirmation note" : "Payout note"}<textarea className="field mt-1.5 min-h-28 py-3" value={note} onChange={(e) => setNote(e.target.value)} required/></label><button className="button-primary w-full">{selected?.mode === "pay" ? "Confirm paid" : "Save payout note"}</button></form></AdminModal></>; }
