import { FormEvent, useState } from "react";
import { Check, NotebookPen } from "lucide-react";
import { AdminModal } from "../components/AdminModal";
import { DataTable } from "../components/DataTable";
import { PageHeader } from "../components/PageHeader";
import { StatusBadge } from "../components/StatusBadge";
import { formatPkr } from "../data/adminData";
import { payouts as initialPayouts } from "../data/payouts";
import type { PayoutRecord } from "../types/admin";

export function PayoutsPage() { const [rows, setRows] = useState(initialPayouts); const [selected, setSelected] = useState<PayoutRecord | null>(null); const [note, setNote] = useState(""); function saveNote(e: FormEvent) { e.preventDefault(); if (!selected) return; setRows((current) => current.map((item) => item.id === selected.id ? { ...item, note } : item)); setSelected(null); } return <><PageHeader eyebrow="PROVIDER FINANCE" title="Payouts" description="Track provider balances and record payout actions in frontend state."/><DataTable rows={rows} rowKey={(row) => row.id} columns={[{ key: "provider", label: "Provider", render: (row) => <strong>{row.provider}</strong> }, { key: "amount", label: "Payout amount", render: (row) => formatPkr(row.amount) }, { key: "pending", label: "Pending balance", render: (row) => formatPkr(row.pendingBalance) }, { key: "paid", label: "Paid amount", render: (row) => formatPkr(row.paidAmount) }, { key: "method", label: "Method", render: (row) => row.method }, { key: "status", label: "Status", render: (row) => <StatusBadge status={row.status === "Paid" ? "Completed" : row.status === "Pending" ? "Pending" : "Provider selection"}/> }, { key: "actions", label: "Actions", render: (row) => <div className="flex gap-2"><button type="button" className="icon-button" title="Add payout note" onClick={() => { setSelected(row); setNote(row.note); }}><NotebookPen size={15}/></button><button type="button" className="button-secondary" disabled={row.status === "Paid"} onClick={() => setRows((current) => current.map((item) => item.id === row.id ? { ...item, status: "Paid", paidAmount: item.amount, pendingBalance: 0 } : item))}><Check size={15}/> Mark paid</button></div> }]}/><AdminModal open={Boolean(selected)} onClose={() => setSelected(null)} title="Add payout note" description={selected?.provider}><form onSubmit={saveNote}><textarea className="field min-h-28 py-3" value={note} onChange={(e) => setNote(e.target.value)} required/><button className="button-primary mt-4 w-full">Save payout note</button></form></AdminModal></>; }
