import { FormEvent, useState } from "react";
import { Edit3, Megaphone, Plus, X } from "lucide-react";
import { AdminModal } from "../components/AdminModal";
import { PageHeader } from "../components/PageHeader";
import { usePreviewState } from "../hooks/usePreviewState";

type Promotion = { id: string; title: string; message: string; placement: "Top ticker" | "Homepage banner" | "Popup"; cta: string; active: boolean; startsAt: string; endsAt: string };
const seed: Promotion[] = [
  { id: "promo-1", title: "Autumn Swat planning", message: "Share your October dates and we will confirm practical provider options by phone.", placement: "Top ticker", cta: "Explore packages", active: true, startsAt: "2026-09-15", endsAt: "2026-10-31" },
  { id: "promo-2", title: "Plan a private family trip", message: "Build a route with hotel, transport, meals, and local support in one request.", placement: "Homepage banner", cta: "Request custom trip", active: true, startsAt: "2026-09-15", endsAt: "2026-12-31" },
];

export function PromotionsPage() {
  const [items, setItems] = usePreviewState("swatstay.admin.promotions.preview", seed);
  const [editing, setEditing] = useState<Promotion | null>(null);
  function save(item: Promotion) { setItems((current) => current.some((entry) => entry.id === item.id) ? current.map((entry) => entry.id === item.id ? item : entry) : [...current, item]); setEditing(null); }
  return <><PageHeader eyebrow="PUBLIC WEBSITE" title="Promotions and announcements" description="Manage homepage banners, optional popups, and the top announcement ticker in browser-only preview state." actions={<button className="button-primary" onClick={() => setEditing({ id: `promo-${Date.now()}`, title: "", message: "", placement: "Top ticker", cta: "Explore packages", active: false, startsAt: "", endsAt: "" })}><Plus size={15}/> Add promotion</button>}/>
    <div className="grid gap-4 lg:grid-cols-3">{(["Top ticker", "Homepage banner", "Popup"] as const).map((placement) => <section key={placement} className="rounded-lg border border-border bg-white p-4"><div className="flex items-center gap-2"><Megaphone size={17} className="text-river"/><h2 className="font-bold text-charcoal">{placement}</h2></div><p className="mt-1 text-xs leading-5 text-stone">{placement === "Popup" ? "Use sparingly for an important notice. It should be dismissible." : "Shown only while the selected dates are active."}</p><div className="mt-4 space-y-3">{items.filter((item) => item.placement === placement).map((item) => <article key={item.id} className="rounded-md border border-border bg-snow p-3"><div className="flex items-start justify-between gap-2"><strong className="text-sm text-charcoal">{item.title || "Untitled promotion"}</strong><span className={`text-xs font-semibold ${item.active ? "text-pine" : "text-stone"}`}>{item.active ? "Active" : "Inactive"}</span></div><p className="mt-2 text-xs leading-5 text-stone">{item.message || "No message entered."}</p><p className="mt-2 text-[11px] text-stone">CTA: {item.cta} · {item.startsAt || "No start"} to {item.endsAt || "No end"}</p><div className="mt-3 flex gap-2"><button className="button-secondary" onClick={() => setEditing(item)}><Edit3 size={14}/> Edit</button><button className="button-secondary" onClick={() => setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, active: !entry.active } : entry))}>{item.active ? "Disable" : "Enable"}</button></div></article>)}{!items.some((item) => item.placement === placement) && <p className="rounded-md bg-snow p-3 text-xs text-stone">No {placement.toLowerCase()} configured.</p>}</div></section>)}</div>
    <PromotionEditor item={editing} onClose={() => setEditing(null)} onSave={save}/>
  </>;
}

function PromotionEditor({ item, onClose, onSave }: { item: Promotion | null; onClose: () => void; onSave: (item: Promotion) => void }) { const [form, setForm] = useState<Promotion | null>(null); const current = form ?? item; function submit(event: FormEvent) { event.preventDefault(); if (!current || !current.title.trim() || !current.message.trim()) return; onSave(current); setForm(null); } return <AdminModal open={Boolean(item)} onClose={onClose} title="Promotion settings" description="Frontend preview only. The public website will read these records from the content API later."><form onSubmit={submit} className="grid gap-4"><label className="label">Title<input required className="field mt-1.5" value={current?.title ?? ""} onChange={(event) => setForm({ ...(current!), title: event.target.value })}/></label><label className="label">Message<textarea required className="field mt-1.5 min-h-24 py-3" value={current?.message ?? ""} onChange={(event) => setForm({ ...(current!), message: event.target.value })}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="label">Placement<select className="field mt-1.5" value={current?.placement} onChange={(event) => setForm({ ...(current!), placement: event.target.value as Promotion["placement"] })}><option>Top ticker</option><option>Homepage banner</option><option>Popup</option></select></label><label className="label">Button label<input className="field mt-1.5" value={current?.cta ?? ""} onChange={(event) => setForm({ ...(current!), cta: event.target.value })}/></label><label className="label">Starts<input type="date" className="field mt-1.5" value={current?.startsAt ?? ""} onChange={(event) => setForm({ ...(current!), startsAt: event.target.value })}/></label><label className="label">Ends<input type="date" className="field mt-1.5" value={current?.endsAt ?? ""} onChange={(event) => setForm({ ...(current!), endsAt: event.target.value })}/></label></div><label className="flex items-center gap-2 text-sm font-semibold text-charcoal"><input type="checkbox" checked={current?.active ?? false} onChange={(event) => setForm({ ...(current!), active: event.target.checked })}/> Active on the public website</label><button className="button-primary">Save promotion</button></form></AdminModal>; }
