import { Ban, Check, Eye, MapPin, X } from "lucide-react";
import { useMemo, useState } from "react";
import { AdminModal } from "../components/AdminModal";
import { FilterBar } from "../components/FilterBar";
import { NotesPanel } from "../components/NotesPanel";
import { PageHeader } from "../components/PageHeader";
import { ProviderStatusBadge } from "../components/ProviderStatusBadge";
import { SearchInput } from "../components/SearchInput";
import { providers as initialProviders } from "../data/adminData";
import type { Provider } from "../types/admin";

type ManagedStatus = Provider["status"] | "Suspended";
type ManagedProvider = Omit<Provider, "status"> & { status: ManagedStatus };

export function ProvidersPage() {
  const [providers, setProviders] = useState<ManagedProvider[]>(initialProviders);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("All");
  const [type, setType] = useState("All");
  const [location, setLocation] = useState("All");
  const [selected, setSelected] = useState<ManagedProvider | null>(null);
  const filtered = useMemo(() => providers.filter((provider) => (!search || provider.name.toLowerCase().includes(search.toLowerCase())) && (status === "All" || provider.status === status) && (type === "All" || provider.serviceType === type) && (location === "All" || provider.location === location)), [providers, search, status, type, location]);
  const update = (id: string, next: ManagedStatus) => setProviders((current) => current.map((provider) => provider.id === id ? { ...provider, status: next } : provider));
  return <><PageHeader eyebrow="PROVIDER NETWORK" title="Providers" description="Review verification, service capacity, pricing, and future payout information."/><FilterBar resultText={`${filtered.length} providers`} onClear={() => { setSearch(""); setStatus("All"); setType("All"); setLocation("All"); }}><SearchInput value={search} onChange={setSearch} placeholder="Search provider"/><select className="field" value={status} onChange={(e) => setStatus(e.target.value)}><option>All</option><option>Pending review</option><option>Approved</option><option>Rejected</option><option>Suspended</option></select><select className="field" value={type} onChange={(e) => setType(e.target.value)}><option>All</option>{["Hotel", "Transport", "Tour guide", "Hiking guide", "Restaurant", "Photographer", "Activity provider"].map((value) => <option key={value}>{value}</option>)}</select><select className="field" value={location} onChange={(e) => setLocation(e.target.value)}><option>All</option>{[...new Set(providers.map((provider) => provider.location))].map((value) => <option key={value}>{value}</option>)}</select></FilterBar><div className="grid gap-4 xl:grid-cols-2">{filtered.map((provider) => <article key={provider.id} className="rounded-lg border border-border bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-charcoal">{provider.name}</h2><p className="mt-1 flex items-center gap-1 text-sm text-stone"><MapPin size={13}/>{provider.location} · {provider.serviceType}</p></div>{provider.status === "Suspended" ? <span className="rounded-md border border-[#e5c1ba] bg-[#fff0ed] px-2 py-1 text-xs font-semibold text-[#9c3f2e]">Suspended</span> : <ProviderStatusBadge status={provider.status}/>}</div><dl className="mt-4 grid grid-cols-3 gap-3 rounded-md bg-snow p-3 text-xs"><Info label="Verification" value={provider.documentsStatus}/><Info label="Capacity" value={provider.capacity}/><Info label="Commission" value={`${provider.commissionRate}%`}/></dl><div className="mt-4 flex flex-wrap gap-2"><button type="button" className="button-secondary" onClick={() => setSelected(provider)}><Eye size={15}/> View details</button><button type="button" className="button-secondary ml-auto" onClick={() => update(provider.id, "Approved")}><Check size={15}/> Approve</button><button type="button" className="button-secondary text-[#9c3f2e]" onClick={() => update(provider.id, "Rejected")}><X size={15}/> Reject</button><button type="button" className="button-secondary text-[#9c3f2e]" onClick={() => update(provider.id, "Suspended")}><Ban size={15}/> Suspend</button></div></article>)}</div><ProviderDetail provider={selected} onClose={() => setSelected(null)}/></>;
}

function ProviderDetail({ provider, onClose }: { provider: ManagedProvider | null; onClose: () => void }) { return <AdminModal open={Boolean(provider)} onClose={onClose} title={provider?.name ?? "Provider"} description="Provider operations record" width="max-w-4xl">{provider && <div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="space-y-5"><DetailSection title="Business and owner" rows={[["Business", provider.name], ["Owner", provider.ownerName], ["Phone", provider.phone], ["Location", provider.location], ["Category", provider.serviceType]]}/><DetailSection title="Service and verification" rows={[["Capacity", provider.capacity], ["Pricing", "Provider price schedule placeholder"], ["Availability", "Calendar connection pending"], ["Documents", provider.documentsStatus], ["Photos", provider.photosStatus], ["Commission", `${provider.commissionRate}%`]]}/><DetailSection title="Bank payout details" rows={[["Account title", "Protected backend field"], ["Method", "Bank or mobile wallet"], ["Verification", "Pending finance review"]]}/><DetailSection title="Booking history" rows={[["Assignments", "No live API records"], ["Completed services", "Future operational value"]]}/></div><NotesPanel title="Provider internal notes"/></div>}</AdminModal>; }
function DetailSection({ title, rows }: { title: string; rows: string[][] }) { return <section><h3 className="border-b border-border pb-2 text-sm font-bold text-pine">{title}</h3><dl className="grid gap-3 pt-3 sm:grid-cols-2">{rows.map(([label, value]) => <div key={label} className="rounded-md bg-snow p-3"><dt className="text-xs text-stone">{label}</dt><dd className="mt-1 text-sm font-semibold text-charcoal">{value}</dd></div>)}</dl></section>; }
function Info({ label, value }: { label: string; value: string }) { return <span><small className="block text-stone">{label}</small><strong className="mt-1 block truncate text-charcoal">{value}</strong></span>; }
