import { FormEvent, useState } from "react";
import { CheckCircle2, Eye, MessageSquarePlus, Star } from "lucide-react";
import { AdminModal } from "../components/AdminModal";
import { PageHeader } from "../components/PageHeader";
import { usePreviewState } from "../hooks/usePreviewState";

type Review = { id: string; traveler: string; booking: string; rating: number; comment: string; status: "Pending" | "Published" | "Hidden"; source: "Traveler form" | "Admin entry"; createdAt: string };
const seed: Review[] = [{ id: "review-1", traveler: "Ayesha Khan", booking: "SS-2048", rating: 5, comment: "The confirmation call made the hotel and pickup plan clear.", status: "Pending", source: "Traveler form", createdAt: "14 Sep 2026" }];

export function ReviewsPage() { const [rows, setRows] = usePreviewState("swatstay.admin.reviews.preview", seed); const [add, setAdd] = useState(false); return <><PageHeader eyebrow="POST-TRIP EXPERIENCE" title="Trip reviews" description="Review traveler feedback after a trip is complete, publish approved feedback, or add a verified offline review." actions={<button className="button-primary" onClick={() => setAdd(true)}><MessageSquarePlus size={15}/> Add verified review</button>}/><section className="overflow-hidden rounded-lg border border-border bg-white"><div className="divide-y divide-border">{rows.map((review) => <article key={review.id} className="grid gap-3 p-4 md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-charcoal">{review.traveler}</strong><span className="text-xs text-stone">{review.booking} · {review.source}</span><span className="inline-flex items-center gap-1 text-xs font-semibold text-[#a66717]"><Star size={13} fill="currentColor"/>{review.rating}/5</span></div><p className="mt-2 text-sm leading-5 text-stone">{review.comment}</p><p className="mt-2 text-xs text-stone">Submitted {review.createdAt}</p></div><div className="flex flex-wrap gap-2"><span className="rounded-md bg-snow px-2 py-1 text-xs font-semibold text-stone">{review.status}</span>{review.status === "Pending" && <button className="button-primary" onClick={() => setRows((current) => current.map((item) => item.id === review.id ? { ...item, status: "Published" } : item))}><CheckCircle2 size={15}/> Publish</button>}<button className="button-secondary" onClick={() => setRows((current) => current.map((item) => item.id === review.id ? { ...item, status: item.status === "Hidden" ? "Pending" : "Hidden" } : item))}><Eye size={15}/>{review.status === "Hidden" ? "Restore" : "Hide"}</button></div></article>)}</div></section><ReviewForm open={add} onClose={() => setAdd(false)} onSave={(review) => { setRows((current) => [{ ...review, id: `review-${Date.now()}`, status: "Pending", source: "Admin entry", createdAt: "Just now" }, ...current]); setAdd(false); }}/></>; }
function ReviewForm({ open, onClose, onSave }: { open: boolean; onClose: () => void; onSave: (review: Omit<Review, "id" | "status" | "source" | "createdAt">) => void }) { const [traveler, setTraveler] = useState(""); const [booking, setBooking] = useState(""); const [rating, setRating] = useState(5); const [comment, setComment] = useState(""); function submit(event: FormEvent) { event.preventDefault(); onSave({ traveler, booking, rating, comment }); setTraveler(""); setBooking(""); setRating(5); setComment(""); } return <AdminModal open={open} onClose={onClose} title="Add verified review" description="Use only feedback collected from a completed trip. It remains pending until reviewed."><form onSubmit={submit} className="grid gap-4"><label className="label">Traveler name<input required className="field mt-1.5" value={traveler} onChange={(e) => setTraveler(e.target.value)}/></label><label className="label">Booking reference<input required className="field mt-1.5" value={booking} onChange={(e) => setBooking(e.target.value)} placeholder="SS-2048"/></label><label className="label">Rating<select className="field mt-1.5" value={rating} onChange={(e) => setRating(Number(e.target.value))}>{[5,4,3,2,1].map((item) => <option key={item} value={item}>{item} out of 5</option>)}</select></label><label className="label">Review<input required className="field mt-1.5" value={comment} onChange={(e) => setComment(e.target.value)}/></label><button className="button-primary">Add for review</button></form></AdminModal>; }
