import { Bell, Languages, Percent, UsersRound } from "lucide-react";
import { PageHeader } from "../components/PageHeader";
import { teamMembers } from "../data/adminData";

export function SettingsPage() {
  return <><PageHeader eyebrow="ADMIN CONFIGURATION" title="Settings" description="Frontend placeholders for controls that will require role checks and API persistence."/><div className="grid gap-4 lg:grid-cols-2"><SettingCard icon={<Percent/>} title="Package commission settings" text="Configure default and service-specific commission rates after finance rules are approved." fields={["Default package commission", "Hotel commission", "Transport commission"]}/><SettingCard icon={<Bell/>} title="Notification settings" text="Choose which booking, payment, provider, and support events alert each operations role." fields={["Booking request alerts", "Payment proof alerts", "Active trip support alerts"]}/><SettingCard icon={<Languages/>} title="Language settings" text="Manage supported admin labels and assignment rules for English, Urdu, and Chinese support." fields={["Default admin language", "Tourist language routing", "Translation review"]}/><section className="panel"><div className="panel-header"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-md bg-mist text-river"><UsersRound size={18}/></span><div><h2 className="panel-title">Team member settings</h2><p className="panel-subtitle">Static roles and queue visibility</p></div></div></div><div className="divide-y divide-border">{teamMembers.map((member) => <div key={member.id} className="flex items-center justify-between gap-3 p-4"><div><strong className="text-sm text-charcoal">{member.name}</strong><p className="mt-1 text-xs text-stone">{member.role}</p></div><span className="rounded-md bg-mist px-2 py-1 text-xs font-semibold text-pine">{member.activeQueue} assigned</span></div>)}</div></section></div></>;
}

function SettingCard({ icon, title, text, fields }: { icon: React.ReactNode; title: string; text: string; fields: string[] }) { return <section className="panel"><div className="panel-header"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-md bg-mist text-river [&>svg]:h-4.5 [&>svg]:w-4.5">{icon}</span><div><h2 className="panel-title">{title}</h2><p className="panel-subtitle mt-1">{text}</p></div></div></div><div className="divide-y divide-border">{fields.map((field) => <div key={field} className="flex items-center justify-between gap-3 p-4"><span className="text-sm font-medium text-charcoal">{field}</span><span className="rounded-md border border-border bg-snow px-2 py-1 text-xs text-stone">Not connected</span></div>)}</div></section>; }
