import { FormEvent, useEffect, useMemo, useState } from "react";
import { CheckCircle2, MessageSquare, Search, Send, UserRoundPlus } from "lucide-react";
import { PageHeader } from "../components/PageHeader";
import { StatusBadge } from "../components/StatusBadge";
import { supportTickets as initialTickets, teamMembers } from "../data/adminData";
import { usePreviewState } from "../hooks/usePreviewState";
import type { SupportMessage, SupportTicket } from "../types/admin";

const initialMessage = (ticket: SupportTicket): SupportMessage => ({ id: `${ticket.id}-opening`, author: ticket.touristName, audience: "Traveler", body: ticket.summary, time: ticket.updatedAt });
const messagesFor = (ticket: SupportTicket) => ticket.messages?.length ? ticket.messages : [initialMessage(ticket)];

export function SupportPage() {
  const [tickets, setTickets] = usePreviewState("swatstay.admin.support.preview", initialTickets);
  const [status, setStatus] = useState("Open");
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState("");
  const [reply, setReply] = useState("");
  const [internal, setInternal] = useState(false);
  const visible = useMemo(() => tickets.filter((ticket) => (status === "All" || ticket.status === status) && `${ticket.id} ${ticket.bookingReference} ${ticket.touristName} ${ticket.issueType}`.toLowerCase().includes(query.toLowerCase())), [query, status, tickets]);
  const selected = tickets.find((ticket) => ticket.id === selectedId) ?? visible[0] ?? tickets[0];

  useEffect(() => { if (visible.length && !visible.some((ticket) => ticket.id === selectedId)) setSelectedId(visible[0].id); }, [selectedId, visible]);

  function updateTicket(id: string, changes: Partial<SupportTicket>) { setTickets((current) => current.map((ticket) => ticket.id === id ? { ...ticket, ...changes, updatedAt: "Just now" } : ticket)); }
  function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected || !reply.trim()) return; const message: SupportMessage = { id: `message-${Date.now()}`, author: internal ? "Internal note · Current admin" : "GFix support", audience: internal ? "Internal" : "Traveler", body: reply.trim(), time: "Just now" }; updateTicket(selected.id, { status: selected.status === "Open" ? "In progress" : selected.status, messages: [...messagesFor(selected), message] }); setReply(""); }
  const openCount = tickets.filter((ticket) => ticket.status === "Open").length;
  const progressCount = tickets.filter((ticket) => ticket.status === "In progress").length;

  return <><PageHeader eyebrow="STEP 6 · SUPPORT AND CLOSE" title="Support workspace" description="Choose one request, see its context, assign the accountable person, reply, and close it when the traveler confirms the solution."/>
    <div className="mb-4 grid gap-3 sm:grid-cols-3"><Summary label="Open requests" value={String(openCount)} note="Need first response"/><Summary label="In progress" value={String(progressCount)} note="Team is coordinating"/><Summary label="Current view" value={status} note="Use filters to focus the queue"/></div>
    <div className="grid gap-4 xl:grid-cols-[300px_minmax(0,1fr)_250px]">
      <aside className="overflow-hidden rounded-lg border border-border bg-white"><div className="border-b border-border p-3"><div className="relative"><Search size={15} className="absolute left-3 top-2.5 text-stone"/><input value={query} onChange={(event) => setQuery(event.target.value)} className="field pl-8 text-sm" placeholder="Search requests"/></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="field mt-2 w-full text-sm"><option>All</option><option>Open</option><option>In progress</option><option>Resolved</option></select></div><div className="max-h-[560px] overflow-y-auto">{visible.length ? visible.map((ticket) => <button type="button" key={ticket.id} onClick={() => setSelectedId(ticket.id)} className={`w-full border-b border-border p-3 text-left last:border-0 ${ticket.id === selected?.id ? "border-l-4 border-l-pine bg-mist" : "hover:bg-snow"}`}><div className="flex items-center justify-between gap-2"><strong className="text-xs text-river">{ticket.id}</strong><StatusBadge status={ticket.status}/></div><h2 className="mt-2 text-sm font-bold text-charcoal">{ticket.issueType}</h2><p className="mt-1 truncate text-xs text-stone">{ticket.touristName} · {ticket.bookingReference}</p><p className="mt-1 line-clamp-2 text-xs leading-4 text-stone">{ticket.summary}</p></button>) : <p className="p-5 text-center text-sm text-stone">No requests match this view.</p>}</div></aside>
      {selected ? <section className="overflow-hidden rounded-lg border border-border bg-white"><div className="border-b border-border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-river">{selected.id}</span><span className="text-xs text-stone">{selected.bookingReference} · {selected.touristName}</span><StatusBadge status={selected.status}/></div><h1 className="mt-2 text-lg font-bold text-charcoal">{selected.issueType}</h1></div><button type="button" disabled={selected.status === "Resolved"} onClick={() => updateTicket(selected.id, { status: "Resolved" })} className="button min-h-9 bg-pine px-3 text-xs text-white hover:bg-[#0e2c22]"><CheckCircle2 size={15}/> Resolve</button></div></div><div className="min-h-[360px] space-y-3 bg-snow p-4">{messagesFor(selected).map((message) => <article key={message.id} className={`max-w-[88%] rounded-md p-3 text-sm leading-5 ${message.audience === "Internal" ? "border border-[#eed7b8] bg-[#fbf3e6]" : message.author === selected.touristName ? "bg-white" : "ml-auto bg-mist"}`}><strong className="block text-xs text-river">{message.author}</strong><p className="mt-1 text-charcoal">{message.body}</p><span className="mt-1 block text-[11px] text-stone">{message.time}{message.audience === "Internal" ? " · Internal only" : " · Traveler-visible preview"}</span></article>)}</div><form onSubmit={send} className="border-t border-border p-3"><label className="mb-2 flex w-fit items-center gap-2 text-xs font-semibold text-stone"><input type="checkbox" checked={internal} onChange={(event) => setInternal(event.target.checked)}/> Internal note only</label><div className="flex gap-2"><input value={reply} onChange={(event) => setReply(event.target.value)} className="field min-w-0 flex-1" placeholder={internal ? "Write an internal handoff note" : "Reply to the traveler"} required/><button className="button min-h-10 bg-pine px-3 text-xs text-white hover:bg-[#0e2c22]"><Send size={15}/> Send</button></div><p className="mt-2 text-[11px] text-stone">Frontend preview: a real API is required to deliver traveler replies.</p></form></section> : <section className="grid min-h-96 place-items-center rounded-lg border border-border bg-white p-5 text-center text-sm text-stone">Select a request from the queue.</section>}
      {selected && <aside className="space-y-4"><section className="rounded-lg border border-border bg-white p-4"><div className="flex items-center gap-2"><UserRoundPlus size={16} className="text-river"/><h2 className="font-bold text-charcoal">Assign or transfer</h2></div><p className="mt-1 text-xs leading-5 text-stone">Only the chosen owner should work this ticket in their Support queue when real role-based access is connected.</p><label className="mt-3 block text-xs font-semibold text-stone">Responsible member<select value={selected.assignedTeamMember} onChange={(event) => updateTicket(selected.id, { assignedTeamMember: event.target.value, status: selected.status === "Open" ? "In progress" : selected.status })} className="field mt-1.5 w-full">{teamMembers.map((member) => <option key={member.id}>{member.name} · {member.role}</option>)}</select></label></section><section className="rounded-lg border border-border bg-white p-4"><div className="flex items-center gap-2"><MessageSquare size={16} className="text-river"/><h2 className="font-bold text-charcoal">Issue context</h2></div><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between gap-3"><dt className="text-stone">Priority</dt><dd className="font-semibold text-charcoal">{selected.priority}</dd></div><div className="flex justify-between gap-3"><dt className="text-stone">Last update</dt><dd className="font-semibold text-charcoal">{selected.updatedAt}</dd></div><div><dt className="text-stone">Tags</dt><dd className="mt-1 flex flex-wrap gap-1">{(selected.tags ?? [selected.issueType]).map((tag) => <span key={tag} className="rounded-md bg-mist px-2 py-1 text-xs font-semibold text-pine">{tag}</span>)}</dd></div></dl></section></aside>}
    </div>
  </>;
}

function Summary({ label, value, note }: { label: string; value: string; note: string }) { return <div className="rounded-lg border border-border bg-white p-3"><span className="block text-xs text-stone">{label}</span><strong className="mt-1 block text-xl text-charcoal">{value}</strong><span className="mt-1 block text-xs text-stone">{note}</span></div>; }
