import { Download, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { PaymentBadge } from "../components/PaymentBadge";
import { StatusBadge } from "../components/StatusBadge";
import { teamMembers } from "../data/adminData";
import { useBookingsPreview } from "../hooks/useBookingsPreview";

function escapeCsv(value: string | number) { const text = String(value); return /[",\n]/.test(text) ? `"${text.replaceAll("\"", "\"\"")}"` : text; }

export function TripsPage() {
  const { bookings } = useBookingsPreview();
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("All"); const [owner, setOwner] = useState("All");
  const rows = useMemo(() => bookings.filter((booking) => (!search || `${booking.reference} ${booking.touristName} ${booking.packageName} ${booking.destination}`.toLowerCase().includes(search.toLowerCase())) && (status === "All" || booking.status === status) && (owner === "All" || booking.assignedSupportMember === owner)), [bookings, owner, search, status]);
  function exportCsv() { const columns = ["Reference", "Tourist", "Phone", "Package", "Destination", "Start date", "End date", "Travelers", "Trip status", "Payment status", "Total", "Paid", "Owner"]; const body = rows.map((booking) => [booking.reference, booking.touristName, booking.phone, booking.packageName, booking.destination, booking.travelStartDate, booking.travelEndDate, booking.travelers, booking.status, booking.paymentStatus, booking.totalAmount, booking.amountPaid, booking.assignedSupportMember].map(escapeCsv).join(",")); const url = URL.createObjectURL(new Blob([[columns.join(","), ...body].join("\n")], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `swatstay-trips-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); }
  return <><PageHeader eyebrow="TRIP OPERATIONS" title="All trips" description="Track every booking across its workflow, assigned owner, payment state, and travel dates. Export the filtered results as CSV." actions={<button type="button" onClick={exportCsv} className="button-primary"><Download size={15}/> Export CSV</button>}/>
    <section className="mb-4 grid gap-3 rounded-lg border border-border bg-white p-3 md:grid-cols-3"><label className="relative"><Search size={16} className="absolute left-3 top-2.5 text-stone"/><input value={search} onChange={(event) => setSearch(event.target.value)} className="field pl-9" placeholder="Trip, tourist, package, destination"/></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="field"><option>All</option>{[...new Set(bookings.map((booking) => booking.status))].map((value) => <option key={value}>{value}</option>)}</select><select value={owner} onChange={(event) => setOwner(event.target.value)} className="field"><option>All</option>{teamMembers.map((member) => <option key={member.id}>{member.name}</option>)}</select></section>
    <div className="mb-3 text-sm text-stone">{rows.length} trip{rows.length === 1 ? "" : "s"} shown</div><section className="overflow-hidden rounded-lg border border-border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left"><thead className="border-b border-border bg-mist text-xs font-semibold uppercase text-stone"><tr><th className="px-4 py-3">Trip</th><th className="px-4 py-3">Traveler</th><th className="px-4 py-3">Dates</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3">Owner</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-border">{rows.map((booking) => <tr key={booking.id} className="hover:bg-snow"><td className="px-4 py-3"><strong className="block text-sm text-river">{booking.reference}</strong><span className="mt-1 block text-sm text-charcoal">{booking.packageName}</span><span className="mt-1 block text-xs text-stone">{booking.destination}</span></td><td className="px-4 py-3"><strong className="block text-sm text-charcoal">{booking.touristName}</strong><span className="mt-1 block text-xs text-stone">{booking.phone}</span></td><td className="px-4 py-3 text-sm text-charcoal">{booking.travelStartDate}<span className="block text-xs text-stone">to {booking.travelEndDate} · {booking.travelers} people</span></td><td className="px-4 py-3"><StatusBadge status={booking.status}/></td><td className="px-4 py-3"><PaymentBadge status={booking.paymentStatus}/></td><td className="px-4 py-3 text-sm text-charcoal">{booking.assignedSupportMember}</td><td className="px-4 py-3 text-right"><Link to={`/bookings/${booking.id}`} className="button-secondary">Open trip</Link></td></tr>)}</tbody></table></div></section>
  </>;
}
