import { Eye, MapPin, Phone } from "lucide-react";
import { Link } from "react-router-dom";
import type { Booking } from "../types/admin";
import { EmptyState } from "./EmptyState";
import { PaymentBadge } from "./PaymentBadge";
import { StatusBadge } from "./StatusBadge";

export function BookingTable({ bookings }: { bookings: Booking[] }) {
  if (!bookings.length) return <EmptyState title="No booking requests found" text="Change the search or filters to view other requests."/>;
  return <div className="overflow-hidden rounded-lg border border-border bg-white"><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1100px] text-left"><thead className="border-b border-border bg-mist text-xs font-semibold uppercase text-stone"><tr><th className="px-4 py-3">Reference</th><th className="px-4 py-3">Tourist</th><th className="px-4 py-3">Package</th><th className="px-4 py-3">Travel date</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3">Support member</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-border">{bookings.map((booking) => <tr key={booking.id} className="hover:bg-snow"><td className="px-4 py-3 text-sm font-bold text-river">{booking.reference}</td><td className="px-4 py-3"><strong className="block text-sm text-charcoal">{booking.touristName}</strong><span className="mt-0.5 block text-xs text-stone">{booking.phone}</span></td><td className="px-4 py-3"><strong className="block max-w-[210px] truncate text-sm text-charcoal">{booking.packageName}</strong><span className="mt-0.5 flex items-center gap-1 text-xs text-stone"><MapPin size={12}/>{booking.destination}</span></td><td className="px-4 py-3 text-sm text-charcoal">{formatDate(booking.travelStartDate)}</td><td className="px-4 py-3"><StatusBadge status={booking.status}/></td><td className="px-4 py-3"><PaymentBadge status={booking.paymentStatus}/></td><td className="px-4 py-3 text-sm text-charcoal">{booking.assignedSupportMember}</td><td className="px-4 py-3 text-right"><Link to={`/bookings/${booking.id}`} className="button-secondary"><Eye size={15}/> View</Link></td></tr>)}</tbody></table></div><div className="divide-y divide-border lg:hidden">{bookings.map((booking) => <article key={booking.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-bold text-river">{booking.reference}</span><h3 className="mt-1 text-base font-bold text-charcoal">{booking.touristName}</h3><p className="mt-1 flex items-center gap-1 text-xs text-stone"><Phone size={12}/>{booking.phone}</p></div><StatusBadge status={booking.status}/></div><p className="mt-3 text-sm font-semibold text-charcoal">{booking.packageName}</p><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><span><small className="block text-stone">Destination</small><strong className="mt-1 block text-charcoal">{booking.destination}</strong></span><span><small className="block text-stone">Travel date</small><strong className="mt-1 block text-charcoal">{formatDate(booking.travelStartDate)}</strong></span></div><div className="mt-4 flex items-center justify-between gap-2"><PaymentBadge status={booking.paymentStatus}/><Link to={`/bookings/${booking.id}`} className="button-secondary"><Eye size={15}/> View request</Link></div></article>)}</div></div>;
}

function formatDate(value: string) { return new Intl.DateTimeFormat("en-PK", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)); }
