import { Image, X } from "lucide-react";
import { useEffect, useState } from "react";
import { AdminModal } from "./AdminModal";
import { adminRequest, getAdminToken } from "../lib/adminApi";

type Media = { id: string; name: string; url?: string | null; mimeType: string };
export function MediaPicker({ label, value, multiple, onChange }: { label: string; value: string[]; multiple?: boolean; onChange: (next: string[]) => void }) {
  const [open, setOpen] = useState(false); const [items, setItems] = useState<Media[]>([]); const [error, setError] = useState("");
  useEffect(() => { if (!open || !getAdminToken()) return; adminRequest<Media[]>("/admin/media").then(setItems).catch((reason: Error) => setError(reason.message)); }, [open]);
  function choose(item: Media) { onChange(multiple ? [...new Set([...value, item.id])] : [item.id]); if (!multiple) setOpen(false); }
  return <div><div className="flex items-center justify-between gap-2"><span className="label">{label}</span><button type="button" className="button-secondary px-2 py-1 text-xs" onClick={() => setOpen(true)}><Image size={14}/> Choose from media</button></div><div className="mt-2 flex flex-wrap gap-2">{value.length ? value.map((path) => <span key={path} className="inline-flex max-w-full items-center gap-1 rounded-md border border-border bg-snow px-2 py-1 text-xs text-stone"><span className="max-w-52 truncate">{path.split("/").pop()}</span><button type="button" onClick={() => onChange(value.filter((item) => item !== path))} aria-label="Remove media"><X size={13}/></button></span>) : <span className="text-xs text-stone">No media selected</span>}</div><AdminModal open={open} onClose={() => setOpen(false)} title={label} description="Select a file from the private Supabase Storage library" width="max-w-3xl">{!getAdminToken() ? <p className="text-sm text-stone">Sign in as admin or operations to select stored media.</p> : error ? <p className="text-sm text-red-700">{error}</p> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.filter((item) => item.mimeType.startsWith("image/")).map((item) => <button type="button" key={item.id} onClick={() => choose(item)} className={`overflow-hidden rounded-md border text-left ${value.includes(item.id) ? "border-river ring-2 ring-river/20" : "border-border"}`}><img src={item.url ?? ""} alt="" className="h-28 w-full object-cover"/><span className="block truncate p-2 text-xs font-semibold text-charcoal">{item.name}</span></button>)}{!items.length && <p className="col-span-full text-sm text-stone">No uploaded images found. Upload one from the Media Library first.</p>}</div>}</AdminModal></div>;
}
