"use client";

import Link from "next/link";
import { CheckCircle2, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

export default function DataDeletionPage() {
  const [sent, setSent] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const [error, setError] = useState("");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!confirmed) { setError("Please confirm that you are requesting deletion of your own information."); return; } setError(""); setSent(true); }
  return <><Header /><main className="section"><div className="container grid max-w-4xl gap-8 lg:grid-cols-[.78fr_1.22fr]"><section><div className="eyebrow">PRIVACY REQUEST</div><h1 className="font-display text-4xl font-bold text-pine">Request data deletion</h1><p className="mt-4 text-sm leading-7 text-stone">Ask the future SwatStay privacy team to review removal or anonymization of your personal information.</p><div className="mt-7 rounded-brand border border-border bg-mist p-4 text-sm leading-6 text-stone"><ShieldCheck size={18} className="mb-2 text-river" /><strong className="text-charcoal">What happens next</strong><ol className="mt-2 list-decimal space-y-1 pl-5"><li>We verify that the request belongs to you.</li><li>We check whether booking, finance, safety, or legal records must be retained.</li><li>We delete or anonymize eligible records and confirm the result.</li></ol></div><p className="mt-5 text-xs leading-5 text-stone">This is a frontend-only request preview. No personal information is transmitted until the privacy workflow is connected to the API.</p><Link href="/privacy" className="mt-4 inline-block text-sm font-semibold text-river">Return to Privacy Policy</Link></section>
    <form onSubmit={submit} className="rounded-brand border border-border bg-white p-5 shadow-editorial md:p-7">{sent ? <div className="py-8 text-center"><CheckCircle2 size={38} className="mx-auto text-pine" /><div className="eyebrow mt-5">REQUEST PREPARED</div><h2 className="font-display text-2xl font-bold text-pine">Your privacy request is ready for review.</h2><p className="mt-3 text-sm leading-6 text-stone">In the live service, the privacy team will verify the request before changing any records.</p><button type="button" onClick={() => { setSent(false); setConfirmed(false); }} className="mt-5 text-sm font-semibold text-river">Submit another request</button></div> : <><h2 className="font-display text-2xl font-bold text-pine">Your details</h2><p className="mt-1 text-sm text-stone">Use the contact details that were used for SwatStay.</p><div className="mt-5 grid gap-4"><label className="text-xs font-semibold text-stone">Full name<input required className="field mt-1 w-full" name="name" placeholder="Your full name" /></label><label className="text-xs font-semibold text-stone">Email or phone<input required className="field mt-1 w-full" name="contact" placeholder="you@example.com or +92..." /></label><label className="text-xs font-semibold text-stone">Booking reference, if available<input className="field mt-1 w-full" name="bookingReference" placeholder="SWT-..." /></label><label className="text-xs font-semibold text-stone">Request details<textarea className="mt-1 min-h-28 w-full rounded-brand border border-border p-3 outline-none focus:border-river focus:ring-1 focus:ring-river" name="message" placeholder="Tell us whether you want account, booking request, or marketing information removed." /></label><label className="flex items-start gap-3 rounded-brand border border-border bg-mist p-3 text-xs leading-5 text-stone"><input type="checkbox" checked={confirmed} onChange={(event) => { setConfirmed(event.target.checked); setError(""); }} className="mt-0.5 h-4 w-4 accent-[#12372A]" />I confirm this request concerns my own information and I understand some records may need to be retained by law or for an active booking.</label>{error && <p role="alert" className="text-xs font-semibold text-[#9c3f2e]">{error}</p>}<button className="button min-h-12 border-pine bg-pine text-white hover:bg-[#0e2c22]">Prepare deletion request</button></div></>}</form></div></main><Footer /></>;
}
