import type { Metadata } from "next";
import { Check, MessageCircle, PhoneCall, ShieldCheck } from "lucide-react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { BookingForm } from "@/components/BookingForm";
import { PageEnter, Reveal } from "@/components/Animated";

const image = "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1800&q=85";

export const metadata: Metadata = { title: "Book a Swat Trip | SwatStay", description: "Submit a call-confirmed Swat booking request for hotels, transport, meals, guides, and local provider support." };
export default function BookingPage() { return <><Header/><PageEnter><main className="bg-snow"><section className="relative overflow-hidden bg-pine text-white"><div className="absolute inset-0 bg-cover bg-center opacity-35" style={{ backgroundImage: `url(${image})` }}/><div className="absolute inset-0 bg-pine/65"/><div className="container relative py-14 md:py-20"><Reveal><div className="eyebrow text-[#c3ebd8]">TRIP REQUEST</div><h1 className="max-w-2xl font-display text-4xl font-bold leading-tight md:text-6xl">Reserve the idea. We confirm the details together.</h1><p className="mt-5 max-w-xl text-base leading-7 text-[#e2f0e7]">Share your preferred route and dates. This is a request, not an instant charge. Our local team calls before anything is booked.</p><a href="https://wa.me/92946000000" target="_blank" rel="noreferrer" className="button mt-7 bg-white text-pine hover:bg-mist"><MessageCircle size={16}/> Plan on WhatsApp</a></Reveal></div></section><section className="section"><div className="container grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-start"><div className="lg:sticky lg:top-28"><div className="eyebrow">HOW IT WORKS</div><h2 className="font-display text-3xl font-bold text-pine md:text-4xl">A clear booking handoff.</h2><p className="mt-4 text-sm leading-6 text-stone">Tell us the essentials and we will use the confirmation call to resolve the practical details.</p><div className="mt-8 space-y-4 border-t border-border pt-5 text-sm text-stone"><p className="flex gap-3"><Check className="mt-0.5 shrink-0 text-river" size={17}/><span><strong className="text-charcoal">Request received</strong><br/>Your details are recorded for this prototype.</span></p><p className="flex gap-3"><PhoneCall className="mt-0.5 shrink-0 text-river" size={17}/><span><strong className="text-charcoal">Call confirmed</strong><br/>We check availability, dates, travelers, and pickup.</span></p><p className="flex gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-river" size={17}/><span><strong className="text-charcoal">Providers coordinated</strong><br/>Only after you approve the final plan.</span></p></div><div className="mt-8 overflow-hidden rounded-brand border border-border bg-white"><div className="h-44 bg-cover bg-center" style={{ backgroundImage: `url(${image})` }}/><div className="p-4"><span className="text-xs font-semibold text-river">SWAT VALLEY · CALL-CONFIRMED</span><p className="mt-2 font-display text-lg font-bold">Your route, stay, and transport in one request.</p></div></div></div><BookingForm packageTitle="Swat Valley trip request" packageImage={image}/></div></section></main></PageEnter><Footer/></>; }
