"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, CalendarDays, CheckCircle2, MapPinned, PhoneCall } from "lucide-react";
import { useState } from "react";
import { Header } from "@/components/Header";

const slides = [
  { eyebrow: "WELCOME TO SWATSTAY", title: "Start with the place you want to remember", text: "Find practical stays across Kalam, Malam Jabba, Bahrain, and Madyan with one clear starting point.", icon: MapPinned, image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1400&q=85" },
  { eyebrow: "MAKE A SIMPLE PLAN", title: "Choose a trip that fits your people", text: "Compare duration, service level, transport, meals, and guide options before you send a request.", icon: CalendarDays, image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1400&q=85" },
  { eyebrow: "CONFIRM WITH A LOCAL TEAM", title: "Your details are checked before booking", text: "We call to confirm dates and availability, then coordinate the local providers for your trip.", icon: PhoneCall, image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1400&q=85" }
];

export default function OnboardingPage() { const [step, setStep] = useState(0); const slide = slides[step]; const Icon = slide.icon; const last = step === slides.length - 1; return <><Header/><main className="min-h-[calc(100vh-76px)] bg-snow py-8 md:py-14"><div className="container grid max-w-5xl gap-8 lg:grid-cols-[1.08fr_.92fr] lg:items-center"><motion.div key={step} initial={{ opacity: 0, x: -16 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .35 }} className="order-2 lg:order-1"><div className="eyebrow flex items-center gap-2"><span className="h-px w-7 bg-current"/>{slide.eyebrow}</div><h1 className="max-w-xl font-display text-4xl font-extrabold leading-tight text-pine md:text-6xl">{slide.title}</h1><p className="mt-5 max-w-lg text-base leading-7 text-stone md:text-lg">{slide.text}</p><div className="mt-8 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-brand bg-pine text-white"><Icon size={21}/></span><span className="text-sm font-semibold text-pine">A clearer way to travel through Swat</span></div><div className="mt-10 flex flex-wrap items-center gap-4"><button onClick={() => setStep((current) => Math.min(current + 1, slides.length - 1))} className="button bg-pine text-white hover:bg-[#0e2c22]">{last ? "Start exploring" : "Continue"}<ArrowRight size={16}/></button>{last && <Link href="/" className="button border-border bg-white text-pine hover:bg-mist">Go to homepage</Link>} {!last && <button onClick={() => setStep(slides.length - 1)} className="text-sm font-semibold text-stone hover:text-pine">Skip</button>}</div><div className="mt-8 flex gap-2" aria-label={`Onboarding step ${step + 1} of ${slides.length}`}>{slides.map((item, index) => <button key={item.eyebrow} aria-label={`Go to step ${index + 1}`} onClick={() => setStep(index)} className={`h-1.5 rounded-full transition-all ${index === step ? "w-10 bg-pine" : "w-5 bg-border"}`}/>)}</div></motion.div><motion.div key={`${step}-image`} initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .4 }} className="order-1 overflow-hidden rounded-brand border border-border bg-white p-3 shadow-editorial lg:order-2"><div className="relative min-h-[390px] overflow-hidden rounded-brand bg-cover bg-center md:min-h-[540px]" style={{ backgroundImage: `url(${slide.image})` }}><div className="absolute inset-0 bg-gradient-to-t from-pine/80 via-pine/10 to-transparent"/><div className="absolute bottom-5 left-5 right-5 rounded-brand border border-white/30 bg-pine/80 p-4 text-white backdrop-blur-sm"><div className="flex items-center justify-between"><span className="text-xs font-semibold tracking-wide text-[#c3ebd8]">SWAT VALLEY</span><CheckCircle2 size={18} className="text-[#c3ebd8]"/></div><strong className="mt-2 block font-display text-xl">Local details, clearly arranged</strong></div></div></motion.div></div></main></>; }
