import type { Metadata } from "next";
import { CheckCircle2, Globe2, Handshake, PhoneCall } from "lucide-react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { PageEnter } from "@/components/Animated";

export const metadata: Metadata = { title: "About SwatStay | Local Swat Travel Support", description: "Learn how SwatStay helps Pakistani and international tourists arrange practical, call-confirmed travel across Swat Valley." };

export default function AboutPage() { return <><Header/><PageEnter><main className="section"><div className="container max-w-5xl"><div className="max-w-3xl"><div className="eyebrow">ABOUT SWATSTAY</div><h1 className="font-display text-4xl font-bold leading-tight text-pine md:text-6xl">A clearer way to arrange travel across Swat Valley.</h1><p className="mt-5 text-base leading-7 text-stone md:text-lg">SwatStay helps tourists compare practical travel packages and send one request for hotels, transport, meals, guides, and activities across Swat.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2"><Story icon={<Handshake/>} title="Built by GFix for local travel" text="GFix is building SwatStay to make local tourism operations easier to understand, coordinate, and improve for both travelers and service providers."/><Story icon={<PhoneCall/>} title="Call-confirmed, not instant" text="A request is not an automatic booking. The GFix team calls to confirm dates, availability, pickup details, payment preference, and provider arrangements."/><Story icon={<CheckCircle2/>} title="A local provider network" text="Hotels, transport operators, restaurants, guides, and activity providers can share their service details for review before receiving relevant requests."/><Story icon={<Globe2/>} title="Support for more travelers" text="The public experience is designed for Pakistani and international tourists, with English, Urdu, and Chinese support planned across the product."/></div><section className="mt-12 border-t border-border pt-8"><div className="eyebrow">HOW THE MODEL WORKS</div><div className="mt-5 grid gap-5 sm:grid-cols-4">{["Choose a package or custom plan", "Send your travel details", "Confirm the practical details by call", "Providers are arranged after confirmation"].map((item, index) => <div key={item} className="border-t border-border pt-4"><span className="text-xs font-bold text-amber">0{index + 1}</span><p className="mt-3 text-sm font-semibold leading-5 text-charcoal">{item}</p></div>)}</div></section></div></main></PageEnter><Footer/></> }
function Story({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="rounded-brand border border-border bg-white p-5"><span className="grid h-10 w-10 place-items-center rounded-md bg-mist text-river [&>svg]:h-5 [&>svg]:w-5">{icon}</span><h2 className="mt-5 font-display text-xl font-bold text-charcoal">{title}</h2><p className="mt-2 text-sm leading-6 text-stone">{text}</p></article>; }
