import { BadgeCheck, CheckCircle2, FileCheck2, HandCoins, MapPin, MessagesSquare, Navigation, ShieldCheck } from "lucide-react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { ProviderRegistrationForm } from "@/components/ProviderRegistrationForm";
import { PageEnter } from "@/components/Animated";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Provider Registration", description: "Register a hotel, transport service, guide, restaurant, or activity service with SwatStay." };

export default function ProviderRegisterPage() { return <><Header/><PageEnter><main className="min-h-screen bg-snow pt-2">
  <section className="border-b border-border bg-snow py-4"><div className="container flex flex-col justify-between gap-3 text-xs text-stone sm:flex-row sm:items-center"><div className="flex flex-wrap items-center gap-2"><a href="/" className="hover:text-pine">Home</a><span>›</span><a href="/provider/register" className="hover:text-pine">Providers</a><span>›</span><span className="font-medium text-charcoal">Service Registration</span></div><div className="inline-flex w-fit items-center gap-2 rounded-md border border-[#c4d7cb] bg-[#e8efea] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.08em] text-pine"><ShieldCheck size={15}/> KP Tourism Department Compliance Verified Registry</div></div></section>
  <section className="border-b border-border bg-white py-10 md:py-16"><div className="container"><div className="max-w-3xl"><div className="eyebrow">VERIFIED VALLEY OPERATIONS NETWORK</div><h1 className="font-display text-4xl font-bold leading-tight tracking-tight text-pine md:text-6xl">Register your tourism service with SwatStay</h1><p className="mt-4 max-w-2xl text-base leading-7 text-stone md:text-lg">Join free during launch. Receive confirmed booking opportunities and pay commission only on successful bookings.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Pillar icon={<Navigation/>} title="Direct matching" text="Local dispatch distribution with zero price undercutting across operators." foot="Protected regional rates"/><Pillar icon={<HandCoins/>} title="Guaranteed clearance" text="Advance digital payouts through verified bank or wallet channels." foot="T+2 settlement cycle"/><Pillar icon={<BadgeCheck/>} title="Verified guests" text="Every traveler is matched with verified identity credentials." foot="Zero fraud liability"/><Pillar icon={<MessagesSquare/>} title="Field support" text="Direct coordination on road blocks, fuel, and route safety." foot="Mingora hub support"/></div></div></section>
  <section className="py-10 md:py-16"><div className="container grid gap-8 lg:grid-cols-12 lg:items-start lg:gap-10"><aside className="flex flex-col gap-6 lg:col-span-5"><Commission/><Workflow/><Prerequisites/><Support/></aside><div className="lg:col-span-7"><ProviderRegistrationForm/></div></div></section>
</main></PageEnter><Footer/></> }

function Pillar({ icon, title, text, foot }: { icon: React.ReactNode; title: string; text: string; foot: string }) { return <div className="flex min-h-44 flex-col justify-between rounded-brand border border-border bg-mist p-4"><div><span className="mb-3 block text-river [&>svg]:h-6 [&>svg]:w-6">{icon}</span><h2 className="font-display text-lg font-semibold text-charcoal">{title}</h2><p className="mt-1 text-sm leading-5 text-stone">{text}</p></div><span className="mt-4 text-[11px] font-semibold uppercase tracking-[.04em] text-pine">{foot}</span></div>; }
function Commission() { return <section className="rounded-brand border border-border bg-white p-5 md:p-6"><div className="flex items-start justify-between gap-3 border-b border-border pb-4"><div><div className="eyebrow mb-1">FEE POLICY</div><h2 className="font-display text-xl font-semibold">Transparent commission</h2></div><span className="rounded-md border border-[#eed7b8] bg-[#faf3e8] px-2.5 py-1 text-[11px] font-semibold text-amber">0 PKR upfront</span></div><p className="mt-4 text-sm leading-5 text-stone">No onboarding, listing, or recurring software membership fees. Commission is deducted only after successful guest checkout or trip completion.</p><div className="mt-4 space-y-2"><Rate name="Hotel & alpine guest houses" value="12%"/><Rate name="Transport & 4x4 fleet" value="10%"/><Rate name="Hiking and trek guides" value="8%"/><Rate name="Restaurants and trout farms" value="5%"/></div></section>; }
function Rate({ name, value }: { name: string; value: string }) { return <div className="flex items-center justify-between rounded-md border border-border bg-snow px-3 py-2"><span className="text-sm font-medium text-charcoal">{name}</span><strong className="font-display text-lg text-pine">{value}</strong></div>; }
function Workflow() { const steps = [["Automated ping", "Direct notification through WhatsApp and SMS dispatch."], ["45-minute window", "Confirm inventory or vehicle readiness."], ["Physical voucher scan", "Guest presents the authorized SwatStay token."], ["Weekly settlement", "Net funds transfer to your designated account."]]; return <section className="rounded-brand border border-border bg-white p-5 md:p-6"><div className="eyebrow mb-1">OPERATIONAL PROTOCOL</div><h2 className="font-display text-xl font-semibold">4-step dispatch workflow</h2><ol className="mt-5 ml-3 space-y-5 border-l border-border">{steps.map(([title, text], index) => <li key={title} className="relative pl-5"><span className="absolute -left-2.5 top-1 grid h-4 w-4 place-items-center rounded-full bg-pine"><span className="h-1.5 w-1.5 rounded-full bg-snow"/></span><h3 className="text-sm font-semibold text-charcoal">{index + 1}. {title}</h3><p className="mt-1 text-xs leading-5 text-stone">{text}</p></li>)}</ol></section>; }
function Prerequisites() { return <section className="rounded-brand border border-border bg-mist p-5 md:p-6"><h2 className="flex items-center gap-2 font-display text-lg font-semibold"><FileCheck2 size={18} className="text-stone"/> Registry prerequisites</h2><ul className="mt-4 space-y-3 text-sm text-stone">{["Original computerized CNIC copy of operating partner", "Swat District municipal permit or KP Tourism license", "Valid vehicle fitness certificate for high-altitude passes", "Active local bank account in the operator's legal title"].map((item) => <li key={item} className="flex items-start gap-2"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-pine"/>{item}</li>)}</ul></section>; }
function Support() { return <section className="rounded-brand border border-border bg-white p-5 md:p-6"><div className="flex items-center gap-2"><MapPin size={20} className="text-pine"/><h2 className="font-display text-lg font-semibold">Mingora field support hub</h2></div><p className="mt-3 text-sm leading-5 text-stone">In-person onboarding, vehicle inspections, and document certification take place at our central office.</p><div className="mt-4 space-y-1 border-t border-border pt-4 text-sm text-stone"><p><strong className="text-charcoal">Desk:</strong> Airport Road, Mingora Hub</p><p><strong className="text-charcoal">Direct line:</strong> +92 946 000000</p><p><strong className="text-charcoal">Email:</strong> providers@swatstay.pk</p><p><strong className="text-charcoal">Hours:</strong> 07:00 to 22:00 PKT</p></div></section>; }
