"use client";

import { Check, ChevronDown, Search } from "lucide-react";
import { useEffect, useRef, useState } from "react";

export type Country = { name: string; code: string; flag: string };

// Kept local for now so the form works without a country-data service.
export const countries: Country[] = [
  ["Afghanistan", "+93", "AF"], ["Albania", "+355", "AL"], ["Algeria", "+213", "DZ"], ["Argentina", "+54", "AR"], ["Australia", "+61", "AU"], ["Austria", "+43", "AT"], ["Bahrain", "+973", "BH"], ["Bangladesh", "+880", "BD"], ["Belgium", "+32", "BE"], ["Brazil", "+55", "BR"], ["Canada", "+1", "CA"], ["Chile", "+56", "CL"], ["China", "+86", "CN"], ["Colombia", "+57", "CO"], ["Croatia", "+385", "HR"], ["Czech Republic", "+420", "CZ"], ["Denmark", "+45", "DK"], ["Egypt", "+20", "EG"], ["Finland", "+358", "FI"], ["France", "+33", "FR"], ["Germany", "+49", "DE"], ["Greece", "+30", "GR"], ["Hong Kong", "+852", "HK"], ["Hungary", "+36", "HU"], ["India", "+91", "IN"], ["Indonesia", "+62", "ID"], ["Iran", "+98", "IR"], ["Iraq", "+964", "IQ"], ["Ireland", "+353", "IE"], ["Italy", "+39", "IT"], ["Japan", "+81", "JP"], ["Jordan", "+962", "JO"], ["Kenya", "+254", "KE"], ["Kuwait", "+965", "KW"], ["Lebanon", "+961", "LB"], ["Malaysia", "+60", "MY"], ["Maldives", "+960", "MV"], ["Mexico", "+52", "MX"], ["Morocco", "+212", "MA"], ["Nepal", "+977", "NP"], ["Netherlands", "+31", "NL"], ["New Zealand", "+64", "NZ"], ["Nigeria", "+234", "NG"], ["Norway", "+47", "NO"], ["Oman", "+968", "OM"], ["Pakistan", "+92", "PK"], ["Philippines", "+63", "PH"], ["Poland", "+48", "PL"], ["Portugal", "+351", "PT"], ["Qatar", "+974", "QA"], ["Romania", "+40", "RO"], ["Russia", "+7", "RU"], ["Saudi Arabia", "+966", "SA"], ["Singapore", "+65", "SG"], ["South Africa", "+27", "ZA"], ["South Korea", "+82", "KR"], ["Spain", "+34", "ES"], ["Sri Lanka", "+94", "LK"], ["Sweden", "+46", "SE"], ["Switzerland", "+41", "CH"], ["Taiwan", "+886", "TW"], ["Thailand", "+66", "TH"], ["Tunisia", "+216", "TN"], ["Turkey", "+90", "TR"], ["Ukraine", "+380", "UA"], ["United Arab Emirates", "+971", "AE"], ["United Kingdom", "+44", "GB"], ["United States", "+1", "US"], ["Uzbekistan", "+998", "UZ"], ["Vietnam", "+84", "VN"], ["Yemen", "+967", "YE"],
].map(([name, code, flag]) => ({ name, code, flag }));

export function CountryPhoneField({ required = true, onCountryChange }: { required?: boolean; onCountryChange?: (country: Country) => void }) { const [country, setCountry] = useState(countries.find((item) => item.name === "Pakistan") ?? countries[0]); const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const ref = useRef<HTMLDivElement>(null); const filtered = countries.filter((item) => `${item.name} ${item.code}`.toLowerCase().includes(query.toLowerCase())); useEffect(() => { const close = (event: MouseEvent) => { if (ref.current && !ref.current.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []); function selectCountry(item: Country) { setCountry(item); onCountryChange?.(item); setOpen(false); setQuery(""); } return <div ref={ref} className="relative"><span className="mb-1 block text-xs font-semibold">Phone number</span><div className="flex h-11 overflow-visible rounded-brand border border-border bg-white focus-within:border-river focus-within:ring-1 focus-within:ring-river"><input type="hidden" name="country" value={country.name}/><input type="hidden" name="countryCode" value={country.code}/><button type="button" onClick={() => setOpen((value) => !value)} className="flex shrink-0 items-center gap-1 border-r border-border px-2.5 text-sm text-charcoal hover:bg-mist"><span className="text-[10px] font-bold text-river">{country.flag}</span><span>{country.code}</span><ChevronDown size={14} className="text-stone"/></button><input required={required} name="phone" inputMode="numeric" pattern="[0-9 ]{7,14}" className="min-w-0 flex-1 rounded-r-brand px-3 outline-none" placeholder="300 1234567"/></div>{open && <div className="absolute left-0 top-full z-50 mt-2 w-72 rounded-brand border border-border bg-white p-2 shadow-editorial"><div className="flex items-center gap-2 rounded-md border border-border px-2"><Search size={15} className="text-stone"/><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} className="h-9 w-full text-sm outline-none" placeholder="Search country or code"/></div><div className="mt-1 max-h-56 overflow-y-auto">{filtered.map((item) => <button type="button" key={item.flag} onClick={() => selectCountry(item)} className="flex w-full items-center justify-between rounded-md px-2 py-2 text-left text-sm hover:bg-mist"><span><strong className="mr-2 text-[10px] text-river">{item.flag}</strong>{item.name}</span><span className="flex items-center gap-1 text-stone">{item.code}{item.name === country.name && <Check size={14} className="text-river"/>}</span></button>)}{!filtered.length && <p className="p-3 text-xs text-stone">No country found.</p>}</div></div>}</div>; }
