"use client";

import { useEffect, useState } from "react";
import { PackageFilters } from "./PackageFilters";
import type { TourPackage } from "@/types/package";

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api/v1";
type ApiPackage = { id: string; name: string; slug: string; summary?: string | null; durationDays: number; basePrice: number; destination: { name: string; slug: string }; items: { serviceType: string; title: string; description?: string | null }[] };
function serviceName(value: string): TourPackage["services"][number] { return (value === "HIKING_GUIDE" ? "Hiking" : value === "RESTAURANT" ? "Meals" : value.charAt(0) + value.slice(1).toLowerCase()) as TourPackage["services"][number]; }
function mapPackage(item: ApiPackage): TourPackage { const services = item.items.map((entry) => serviceName(entry.serviceType)); return { slug: item.slug, title: item.name, destination: item.destination.name, route: item.destination.name, duration: `${item.durationDays} days`, type: "Private", tier: "Standard", price: item.basePrice, image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1400&q=85", description: item.summary ?? "A call-confirmed Swat tour package with local service arrangements.", services, serviceDetails: item.items.map((entry) => ({ service: serviceName(entry.serviceType), providerName: "Provider to be confirmed", title: entry.title, description: entry.description ?? "Details confirmed by the GFix team during the booking call.", assignmentStatus: "pending" })), itinerary: [] }; }
export function PackageCatalog() { const [items, setItems] = useState<TourPackage[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { fetch(`${API_BASE_URL}/packages`).then(async (response) => { if (!response.ok) throw new Error("Package catalog is unavailable right now."); return response.json(); }).then((body: { data: ApiPackage[] }) => setItems(body.data.map(mapPackage))).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Package catalog is unavailable right now.")).finally(() => setLoading(false)); }, []); if (loading) return <div className="rounded-brand border border-border bg-white p-6 text-sm text-stone">Loading current packages...</div>; if (error) return <div role="alert" className="rounded-brand border border-red-200 bg-red-50 p-6 text-sm text-red-700">{error}</div>; return <PackageFilters items={items}/>; }
