"use client";

import { ArrowRight, BadgeCheck, CarFront, CheckCircle2, FileText, Hotel, ImagePlus, Mountain, ShieldCheck, Utensils } from "lucide-react";
import { useState } from "react";
import Link from "next/link";
import { CustomSelect } from "./CustomSelect";

const categories = [{ key: "hotel", title: "Hotel & guesthouse", detail: "Kalam / Malam Jabba", icon: Hotel }, { key: "transport", title: "Transport & 4x4", detail: "Jeep / Hiace fleet", icon: CarFront }, { key: "guide", title: "Guide & hiking", detail: "Certified local guide", icon: Mountain }, { key: "restaurant", title: "Restaurant & meals", detail: "Local food service", icon: Utensils }];

export function ProviderRegistrationForm() {
  const [category, setCategory] = useState("hotel");
  const [sent, setSent] = useState(false);
  const [files, setFiles] = useState<Record<string, string>>({});
  const [privacyAccepted, setPrivacyAccepted] = useState(false);
  const [privacyError, setPrivacyError] = useState("");
  const [submitError, setSubmitError] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [reference, setReference] = useState("");
  if (sent) return <div className="rounded-brand border border-border bg-white p-8 text-center shadow-editorial"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full border border-[#c4d7cb] bg-[#e8efea] text-pine"><BadgeCheck size={34}/></span><div className="eyebrow mt-5">REGISTRATION DOCKET SUBMITTED</div><h2 className="font-display text-2xl font-bold text-pine">Your service is with the field team</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-stone">Your credentials have been routed for review. A local coordinator will contact you to confirm the next inspection step.</p><div className="mx-auto mt-6 max-w-sm rounded-brand border border-border bg-mist p-4 text-left text-sm text-charcoal"><p><strong>Tracking ID:</strong> <span className="font-mono text-river">{reference || "Pending review"}</span></p><p className="mt-1"><strong>Review desk:</strong> Mingora Field Office</p><p className="mt-1"><strong>Estimated review:</strong> Within 24 business hours</p></div><button type="button" onClick={() => { setSent(false); setReference(""); }} className="mt-6 text-sm font-semibold text-river">Register another provider</button></div>;
  const upload = (name: string, fileList: FileList | null) => { if (fileList?.[0]) setFiles((current) => ({ ...current, [name]: fileList[0].name })); };
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!privacyAccepted) { setPrivacyError("Please agree to the Privacy Policy and Terms before submitting registration."); return; } setPrivacyError(""); setSubmitError(""); setSubmitting(true); const data = new FormData(event.currentTarget); const password = String(data.get("password") ?? ""); const confirmPassword = String(data.get("confirmPassword") ?? ""); if (password !== confirmPassword) { setSubmitError("Passwords do not match."); setSubmitting(false); return; } const categoryMap: Record<string, string> = { hotel: "HOTEL", transport: "TRANSPORT", guide: "HIKING_GUIDE", restaurant: "RESTAURANT" }; const payload = { businessName: String(data.get("businessName") ?? ""), ownerName: String(data.get("ownerName") ?? ""), email: String(data.get("email") ?? ""), phone: String(data.get("phone") ?? ""), password, serviceCategory: categoryMap[category], location: String(data.get("location") ?? ""), address: String(data.get("address") ?? ""), capacity: Number(data.get("capacity") ?? 0) || undefined, description: String(data.get("description") ?? ""), consent: true }; try { const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api/v1"}/providers/register`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => null) as { message?: string; data?: { reference?: string } } | null; if (!response.ok) throw new Error(Array.isArray(body?.message) ? body.message.join(" ") : body?.message ?? "Unable to submit provider registration."); setReference(body?.data?.reference ?? ""); setSent(true); } catch (reason) { setSubmitError(reason instanceof Error ? reason.message : "Unable to submit provider registration."); } finally { setSubmitting(false); } }
  return <form onSubmit={submit} className="rounded-brand border border-border bg-white p-5 shadow-editorial sm:p-7">
    <div className="border-b border-border pb-5"><div className="eyebrow mb-1">PROVIDER REGISTRATION DOCKET</div><h2 className="font-display text-2xl font-bold text-pine">Register your operating unit</h2><p className="mt-2 text-sm leading-6 text-stone">Complete each section so our field team can review your service accurately.</p></div>
    <Step number="1" title="Primary provider category"><p className="mb-4 text-sm text-stone">Select the service you want to receive requests for.</p><div className="grid gap-2 sm:grid-cols-2">{categories.map(({ key, title, detail, icon: Icon }) => <button key={key} type="button" onClick={() => setCategory(key)} className={`flex min-h-28 flex-col justify-between rounded-brand border p-3 text-left transition ${category === key ? "border-pine bg-[#e8efea]" : "border-border bg-white hover:border-river hover:bg-mist"}`}><Icon size={21} className={category === key ? "text-pine" : "text-stone"}/><span><strong className="block text-sm text-charcoal">{title}</strong><small className="text-xs text-stone">{detail}</small></span></button>)}</div><input type="hidden" name="serviceCategory" value={category}/></Step>
    <Step number="2" title="Contact and operation"><div className="grid gap-4 sm:grid-cols-2"><Field label="Business name"><input required name="businessName" className="field mt-1 w-full" placeholder="Your hotel, restaurant, or service"/></Field><Field label="Owner / contact name"><input required name="ownerName" className="field mt-1 w-full" placeholder="Full name"/></Field><Field label="Phone / WhatsApp"><input required name="phone" className="field mt-1 w-full" placeholder="+92 300 1234567"/></Field><Field label="Email address"><input required type="email" name="email" className="field mt-1 w-full" placeholder="you@business.com"/></Field><Field label="Account password"><input required minLength={8} type="password" name="password" className="field mt-1 w-full" placeholder="At least 8 characters"/></Field><Field label="Confirm password"><input required minLength={8} type="password" name="confirmPassword" className="field mt-1 w-full" placeholder="Re-enter password"/></Field><CustomSelect label="Primary location" name="location" placeholder="Choose a location" options={[{label:"Mingora / Saidu Sharif",value:"mingora"},{label:"Kalam",value:"kalam"},{label:"Bahrain",value:"bahrain"},{label:"Madyan",value:"madyan"},{label:"Malam Jabba",value:"malam-jabba"}]}/><Field label="Capacity"><input required name="capacity" className="field mt-1 w-full" placeholder="Guests, vehicles, or group size"/></Field></div><Field label="Business address"><textarea required name="address" rows={3} className="mt-1 w-full rounded-brand border border-border p-3 outline-none focus:border-river focus:ring-1 focus:ring-river" placeholder="Street, landmark, access notes, or meeting point"/></Field></Step>
    <Step number="3" title={`${category === "transport" ? "Fleet" : category === "guide" ? "Guide" : category === "restaurant" ? "Food service" : "Property"} specifications`}><div className="grid gap-4 sm:grid-cols-2">{category === "transport" ? <><Field label="Vehicle model"><input required name="vehicleModel" className="field mt-1 w-full" placeholder="Toyota Prado TX / Hiace"/></Field><Field label="Model year"><input required name="vehicleYear" type="number" className="field mt-1 w-full" placeholder="2018"/></Field><Field label="Passenger capacity"><input required name="passengerCapacity" type="number" className="field mt-1 w-full" placeholder="7"/></Field></> : category === "guide" ? <><Field label="KP license number"><input name="guideLicense" className="field mt-1 w-full" placeholder="KP-TR-2024-XXXX"/></Field><Field label="Spoken languages"><input required name="languages" className="field mt-1 w-full" placeholder="Urdu, Pashto, English"/></Field></> : <><Field label={category === "hotel" ? "Room / unit count" : "Seating capacity"}><input required name="unitCount" type="number" className="field mt-1 w-full" placeholder="12"/></Field><Field label={category === "hotel" ? "Room level" : "Speciality"}><input required name="speciality" className="field mt-1 w-full" placeholder={category === "hotel" ? "Standard, family, premium" : "Local trout, traditional meals"}/></Field></>}<Field label="Service description"><textarea required name="description" rows={3} className="mt-1 w-full rounded-brand border border-border p-3 outline-none focus:border-river focus:ring-1 focus:ring-river sm:col-span-2" placeholder="What should a traveler know about your service?"/></Field></div></Step>
    <Step number="4" title="Pricing and availability"><div className="grid gap-4 sm:grid-cols-2"><Field label="Base off-season rate (PKR)"><input required name="baseRate" type="number" className="field mt-1 w-full" placeholder="8000"/></Field><CustomSelect label="Availability window" name="availability" value="year-round" options={[{label:"365 days year-round",value:"year-round"},{label:"Summer peak, May to September",value:"summer"},{label:"Winter focus, December to March",value:"winter"},{label:"Weekend and holiday only",value:"weekend"}]}/></div><div className="mt-4 flex gap-2 rounded-brand border border-border bg-mist p-3 text-xs leading-5 text-stone"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-river"/>If a room is overbooked or a vehicle fails, an equivalent or higher-grade replacement should be arranged within 60 minutes.</div></Step>
    <Step number="5" title="Regulatory document verification"><div className="grid gap-3 sm:grid-cols-3"><UploadCard icon={<FileText/>} title="CNIC front & back" hint="PDF or clear JPG" value={files.cnic} onChange={(files) => upload("cnic", files)}/><UploadCard icon={<FileText/>} title="Business permit" hint="SECP / KP Tourism cert" value={files.permit} onChange={(files) => upload("permit", files)}/><UploadCard icon={<ImagePlus/>} title="Property / fleet photos" hint="Minimum 4 photos" value={files.photos} multiple onChange={(files) => upload("photos", files)}/></div></Step>
    <Step number="6" title="Bank payout designation"><div className="grid gap-4 sm:grid-cols-2"><CustomSelect label="Bank / channel" name="bank" value="alfalah" options={[{label:"Bank Alfalah",value:"alfalah"},{label:"Meezan Bank",value:"meezan"},{label:"HBL",value:"hbl"},{label:"Easypaisa merchant",value:"easypaisa"},{label:"JazzCash corporate",value:"jazzcash"}]}/><Field label="Account title / beneficiary"><input required name="accountTitle" className="field mt-1 w-full" placeholder="Matching legal name"/></Field><Field label="IBAN / account number"><input required name="iban" className="field mt-1 w-full" placeholder="PK00ALFH0000..."/></Field></div></Step>
    <label className="mt-6 flex items-start gap-3 rounded-brand border border-border bg-mist p-3 text-sm leading-5 text-charcoal"><input required name="compliance" type="checkbox" className="mt-1 h-4 w-4 accent-[#12372A]"/>I agree to provide services under SwatStay safety guidelines and transparent guest pricing. I verify that all submitted documentation is current and lawful.</label><label className="mt-3 flex items-start gap-3 text-xs leading-5 text-stone"><input required name="legalAgreement" type="checkbox" checked={privacyAccepted} onChange={(event) => { setPrivacyAccepted(event.target.checked); if (event.target.checked) setPrivacyError(""); }} className="mt-0.5 h-4 w-4 accent-[#12372A]"/>I agree to the <Link href="/terms" className="font-semibold text-river">Terms and Conditions</Link> and understand how provider information is used under the <Link href="/privacy" className="font-semibold text-river">Privacy Policy</Link>.</label>{privacyError && <p role="alert" className="mt-3 text-xs font-semibold text-[#9c3f2e]">{privacyError}</p>}{submitError && <p role="alert" className="mt-3 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-xs font-semibold text-[#9c3f2e]">{submitError}</p>}<button disabled={submitting} className="button mt-5 min-h-12 w-full bg-pine text-white hover:bg-[#0e2c22] disabled:cursor-wait disabled:opacity-60">{submitting ? "Submitting registration..." : "Submit provider registration"} <ArrowRight size={17}/></button><p className="mt-3 flex items-center justify-center gap-2 text-center text-xs text-stone"><ShieldCheck size={15} className="text-river"/> Your service stays pending until the team completes review.</p>
  </form>;
}

function Step({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="mt-6 border-t border-border pt-6"><div className="mb-4 flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded-full bg-pine text-xs font-bold text-white">{number}</span><h3 className="font-display text-lg font-semibold text-charcoal">{title}</h3></div>{children}</section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs font-semibold text-stone">{label}{children}</label>; }
function UploadCard({ icon, title, hint, value, multiple, onChange }: { icon: React.ReactNode; title: string; hint: string; value?: string; multiple?: boolean; onChange: (files: FileList | null) => void }) { return <div className="flex min-h-40 flex-col items-center justify-center rounded-brand border border-dashed border-border bg-snow p-3 text-center transition hover:border-river"><span className="mb-2 text-stone [&>svg]:h-7 [&>svg]:w-7">{icon}</span><strong className="text-sm text-charcoal">{title}</strong><span className="mt-1 text-[11px] text-stone">{hint}</span><label className="mt-3 cursor-pointer rounded-md border border-border bg-white px-3 py-1.5 text-[11px] font-semibold text-pine hover:bg-mist">{value ? "Replace file" : "Browse file"}<input type="file" hidden multiple={multiple} accept="image/*,.pdf,.zip" onChange={(event) => onChange(event.target.files)}/></label><span className={`mt-2 max-w-full truncate text-[11px] ${value ? "font-semibold text-pine" : "text-stone"}`}>{value ?? "Pending"}</span></div>; }
