"use client";

import { CloudRain, CloudSun, LoaderCircle, Sun, Wind } from "lucide-react";
import { useEffect, useState } from "react";
import { getWeather } from "@/lib/api";

type Forecast = { destination: string; current?: { temperature_2m?: number; apparent_temperature?: number; precipitation_probability?: number; wind_speed_10m?: number; weather_code?: number }; daily?: { time?: string[]; temperature_2m_max?: number[]; temperature_2m_min?: number[]; precipitation_probability_max?: number[]; weather_code?: number[] } };
function weatherLabel(code = 0) { if (code >= 51 && code <= 99) return "Rain or showers"; if (code >= 1 && code <= 3) return "Partly cloudy"; if (code === 0) return "Clear"; return "Changing conditions"; }
function WeatherIcon({ code }: { code?: number }) { return code && code >= 51 ? <CloudRain size={18}/> : code && code > 0 ? <CloudSun size={18}/> : <Sun size={18}/>; }

export function WeatherPreview({ destination }: { destination: string }) {
  const [forecast, setForecast] = useState<Forecast | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { let active = true; void getWeather(destination).then((data) => { if (active) setForecast(data as Forecast); }).catch((reason: unknown) => { if (active) setError(reason instanceof Error ? reason.message : "Weather unavailable"); }); return () => { active = false; }; }, [destination]);
  return <section className="rounded-brand border border-border bg-white p-4 md:p-5"><div className="flex items-start justify-between gap-3"><div><div className="eyebrow mb-1">TRIP WEATHER</div><h2 className="font-display text-xl font-bold text-charcoal">Planning forecast for {destination}</h2><p className="mt-1 text-xs text-stone">Open-Meteo forecast · advisory only</p></div><Wind size={20} className="text-river"/></div>{!forecast && !error && <p className="mt-4 flex items-center gap-2 text-sm text-stone"><LoaderCircle size={16} className="animate-spin"/> Loading forecast...</p>}{error && <p className="mt-4 rounded-md bg-snow p-3 text-sm text-stone">Weather is unavailable right now. Check again closer to departure.</p>}{forecast?.current && <><div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="rounded-md bg-mist p-3"><span className="text-xs text-stone">Now</span><strong className="mt-1 block text-xl text-pine">{Math.round(forecast.current.temperature_2m ?? 0)}°C</strong><span className="text-xs text-stone">{weatherLabel(forecast.current.weather_code)}</span></div><div className="rounded-md bg-snow p-3"><span className="text-xs text-stone">Rain chance</span><strong className="mt-1 block text-xl text-charcoal">{forecast.current.precipitation_probability ?? 0}%</strong></div><div className="rounded-md bg-snow p-3"><span className="text-xs text-stone">Wind</span><strong className="mt-1 block text-xl text-charcoal">{Math.round(forecast.current.wind_speed_10m ?? 0)} km/h</strong></div></div><div className="mt-4 grid grid-cols-3 gap-2">{forecast.daily?.time?.slice(0, 3).map((date, index) => <div key={date} className="rounded-md border border-border p-2 text-center"><span className="block text-[11px] text-stone">{new Date(date).toLocaleDateString("en-GB", { weekday: "short" })}</span><span className="mx-auto my-2 grid h-8 w-8 place-items-center rounded-md bg-mist text-river"><WeatherIcon code={forecast.daily?.weather_code?.[index]}/></span><strong className="text-sm text-charcoal">{Math.round(forecast.daily?.temperature_2m_max?.[index] ?? 0)}°</strong><span className="block text-[11px] text-stone">Rain {forecast.daily?.precipitation_probability_max?.[index] ?? 0}%</span></div>)}</div></>}{forecast && <p className="mt-3 text-[11px] leading-4 text-stone">Forecast conditions can change. Confirm road and safety decisions with the GFix team.</p>}</section>;
}
