import { ArrowDown, Check, MapPin, PhoneCall, ShieldCheck } from "lucide-react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { CustomTripForm } from "@/components/CustomTripForm";
import { PageEnter, Reveal } from "@/components/Animated";

const image = "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1800&q=85";

export default function CustomTripPage() {
  return <><Header/><PageEnter><main className="bg-snow">
    <section className="relative overflow-hidden bg-pine text-white"><div className="absolute inset-0 bg-cover bg-center opacity-35" style={{ backgroundImage: `url(${image})` }}/><div className="absolute inset-0 bg-pine/65"/><div className="container relative grid gap-10 py-16 md:py-24 lg:grid-cols-[1.05fr_.95fr] lg:items-end"><Reveal><div><div className="eyebrow flex items-center gap-2 text-[#c3ebd8]"><span className="h-px w-7 bg-current"/>CUSTOM TRIP STUDIO</div><h1 className="max-w-3xl font-display text-4xl font-bold leading-tight md:text-6xl">A Swat trip shaped around your people.</h1><p className="mt-5 max-w-xl text-base leading-7 text-[#e2f0e7] md:text-lg">Start with the places and pace you want. We will turn your brief into a practical route with local stays, transport, meals, and guides.</p><a href="#trip-form" className="button mt-8 bg-white text-pine hover:bg-mist">Build your trip <ArrowDown size={16}/></a></div></Reveal><div className="hidden justify-end lg:flex"><div className="max-w-xs border-l border-white/30 pl-5 text-sm text-[#d6e8dc]"><p className="font-semibold text-white">Local planning, without the guesswork.</p><p className="mt-2 leading-6">A real team member reviews your request and calls before anything is booked.</p></div></div></div></section>
    <section className="section"><div className="container grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-start"><div className="lg:sticky lg:top-28"><div className="eyebrow">PLAN WITH CONTEXT</div><h2 className="font-display text-3xl font-bold text-pine md:text-4xl">The details that make a route feel like yours.</h2><p className="mt-4 text-sm leading-6 text-stone">Use the brief to tell us what you care about. You do not need to know the perfect itinerary yet.</p><div className="mt-8 space-y-4 border-t border-border pt-5 text-sm text-stone"><p className="flex gap-3"><Check className="mt-0.5 shrink-0 text-river" size={17}/><span><strong className="text-charcoal">Flexible destinations</strong><br/>Mix Kalam, Malam Jabba, Bahrain, Madyan, and quieter valleys.</span></p><p className="flex gap-3"><PhoneCall className="mt-0.5 shrink-0 text-river" size={17}/><span><strong className="text-charcoal">A call before confirmation</strong><br/>We clarify availability, pickup, and the right service level.</span></p><p className="flex gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-river" size={17}/><span><strong className="text-charcoal">Local details checked</strong><br/>Your request is prepared for reviewed local providers.</span></p></div><div className="mt-8 overflow-hidden rounded-brand border border-border bg-white"><div className="h-40 bg-cover bg-center" style={{ backgroundImage: `url(${image})` }}/><div className="p-4"><p className="flex items-center gap-2 text-xs font-semibold text-river"><MapPin size={14}/> Swat Valley</p><p className="mt-2 font-display text-lg font-bold">From first idea to a clear plan</p></div></div></div><div id="trip-form"><CustomTripForm/></div></div></section>
  </main></PageEnter><Footer/></>;
}
