import type { Metadata } from "next";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

export const metadata: Metadata = { title: "Terms and Conditions | SwatStay", description: "Review SwatStay booking requests, confirmation calls, payments, provider coordination, cancellation, and support terms." };

export default function TermsPage() {
  return <><Header /><main className="section"><article className="container max-w-3xl"><div className="eyebrow">SWATSTAY TERMS</div><h1 className="font-display text-4xl font-bold text-pine md:text-5xl">Terms and Conditions</h1><p className="mt-4 text-sm leading-7 text-stone">Last updated: 17 September 2026. These terms apply to SwatStay booking requests and the future call-confirmed travel service.</p><div className="prose prose-stone mt-10 max-w-none"><Section title="Booking requests and confirmation">Submitting a package, custom-trip, or support request does not confirm a booking. GFix confirms traveler details, availability, provider arrangements, final price, payment requirements, and cancellation rules by call before services are booked.</Section><Section title="Prices, payments, and proof">A displayed price is a starting price unless the confirmation call states otherwise. Advance or full payment may be required after confirmation. Payment proof is reviewed by the GFix team and does not automatically confirm payment or services.</Section><Section title="Providers and service changes">Hotels, transport, guides, restaurants, activities, and other services are assigned after confirmation. A provider may be replaced with an equivalent suitable option when availability, safety, weather, road conditions, or operational needs require it. The team will communicate material changes.</Section><Section title="Cancellation, refunds, and rescheduling">Cancellation and refund eligibility depends on the confirmed provider policy, service date, and services already arranged. Weather and road conditions can require a safe reschedule or route change. The final applicable rules are shared during confirmation and recorded with the booking.</Section><Section title="Traveler responsibilities">Travelers must provide accurate contact, identity, group, health, and travel details that are relevant to the requested services. Travelers must follow reasonable safety directions, hotel rules, transport rules, and local laws.</Section><Section title="Support and emergencies">Support availability and contact methods are shown on the booking and dashboard. During an active trip, contact the team promptly about a service issue so it can be recorded and coordinated. The platform is not an emergency-services replacement.</Section><Section title="Prototype status">Until the backend is launched, forms, payments, chat, QR vouchers, and dashboard actions are UI demonstrations only. They do not create a binding booking, account, payment, or support ticket.</Section></div></article></main><Footer /></>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2>{title}</h2><p>{children}</p></section>; }
